### ISSUE TITLE
suggestions: to ensure vehicle spawn and removal at terminal stop

### ISSUE THREAD

**Issue by PC28K** [klyte45/TransportLinesManager#101]
・when the bus is spawn, we suggest that you head to the terminal stop and start running from there.
In my area, most of the bus routes start from garages(a station in the garage), few vehicles can be seen moving from the garage to the middle of the line. Even if there is a case of moving to an empty car, it goes to the starting point, not the middle of the line. In this model, I don't think the current way is appropriate.
i think, perhaps in this case, the spawn interval should also be revised.

・ It would be nice if the work was carried out only at the terminal stop when the finished vehicle returns to the garage.
even when the bus finishes, it returns to the stop in front of the garage and finishes. And when the bus return garage, it's a long-standing tradition for the CSL to kidnap passengers. maybe we can work it out with the kidnapping problem.

I don't know what it's like technically, but I think it'd be nice if it was possible.
please review it.

**Comment by wjhunt78** [comment]
Regarding your second issue: I have been using Transport Vehicle Return Patch for a long time now and it works very well. When it's time for a vehicle to return to the depot, it continues its route first to drop off the remaining passengers at their desired stop, then returns to the depot.

**Comment by klyte45** [comment]
> Regarding your second issue: I have been using Transport Vehicle Return Patch for a long time now and it works very well. When it's time for a vehicle to return to the depot, it continues its route first to drop off the remaining passengers at their desired stop, then returns to the depot.

I suggest you to open a separate issue to this. I believe the terminal feature can improve it even more.

**Comment by wjhunt78** [comment]
There is no issue for me here, I only placed this comment to help PC28K solve his kidnapping problem :-)

**Comment by klyte45** [comment]
Sorry, I misread 😅

So I would ask to @PC28K to separate it in two issues - one for the spawning and another for returning. I didn't payed enough attention to notice that there are 2 features in one single issue - and them may can be delivered separately

**Comment by PC28K** [comment]
> Regarding your second issue: I have been using Transport Vehicle Return Patch for a long time now and it works very well. When it's time for a vehicle to return to the depot, it continues its route first to drop off the remaining passengers at their desired stop, then returns to the depot.

Thank you for telling me. actually, I've used it before, but I felt sorry for the driver who couldn't leave work forever if the passenger kept riding 😭

**Comment by PC28K** [comment]
> Sorry, I misread 😅
> 
> So I would ask to @PC28K to separate it in two issues - one for the spawning and another for returning. I didn't payed enough attention to notice that there are 2 features in one single issue - and them may can be delivered separately

yeah, that's right. How can you do that?
