### ISSUE TITLE
Question regarding right-clicking stops in the line map

### ISSUE THREAD

**Issue by Oninaig** [klyte45/TransportLinesManager#109]
When you right click on a particular stop on the line map, it turns the icon into a star. What exactly does that do?

![image](https://user-images.githubusercontent.com/2964006/122463707-f00d4900-cf83-11eb-9b7a-89913fece6e8.png)
![image](https://user-images.githubusercontent.com/2964006/122463725-f69bc080-cf83-11eb-97aa-eed01ea450a5.png)

**Comment by comahoney21** [comment]
It essentially turns the stop into a "mandatory stop", meaning it will force a bus to stop there, even when no passengers are looking to board or alight. The regular circles mean it's an "optional" or "express" stop, so the bus won't stop unless there are passengers looking to board or alight!

**Comment by Oninaig** [comment]
Thanks!
