### ISSUE TITLE
Public Transport Income Reduced to Zero

### ISSUE THREAD

**Issue by KingSS007** [klyte45/TransportLinesManager#112]
Changing the public transport ticket price for any line from the default value will result in a zero income for all the lines. 
As per the mentioned incompatible mods in the steam workshop, I don't have either IPT2 or Resize it, neither the Ticket price customizer mod. I do have Advanced vehicle options Mod, TMPE President edition. 
Please help me solving this issue.
Thanks.

**Comment by l-c-r-ant** [comment]
I'm having the same issue.  If I watch the transportation line overview, right at the beginning of the cycle the values VERY briefly flash to green values and then immediately go back to red.  If I have a line detail window up, you can see that the values flash green right when the new period is added to the financial report.

**Comment by klyte45** [comment]
Guys, double check if you haven't turned on any of the Free Public transport policies (for match day, district or whole city)
If not, reopen this.
