### ISSUE TITLE
Bus Frequency

### ISSUE THREAD

**Issue by bornatoviski** [klyte45/TransportLinesManager#116]
It's not a problem, just a question. Have plans to configure the bus interval per line, the frequency? for example: the line has a frequency of 10 minutes for each bus. 
Currently, almost all buses are together, one after the other and I remember that past versions of the mod had this configuration.

**Comment by klyte45** [comment]
I guess you are getting confused with the IPT, once TLM never had a timing function like this. In the TLM we have the vehicle distribution by the stops for buses, trolleybus and trams. But in the latest version (14) was added a feature to make these vehicles only stop in the stops if there's any passenger exchange to be done, and this may cause vehicle bunches in the last stop. If you want the vehicles to obey a time distance, so disable these options here:
![image](https://user-images.githubusercontent.com/11671356/135971378-959e950a-f622-487c-b8fe-854982e76d70.png)

I'll close this, but fell free to ask more information about.
