### ISSUE TITLE
Release waiting CIMs when transit line stops service

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#117]
Not sure if this should be handled by this mod or by TM-PE, but if the transit lines stops service (ie in some hours, the transit line should have 0 vehicles in service) then the CIMS waiting should just cancel their journey or recalculate their journey.

It is just that eg if I have several bus lines that have 0 vehicles at night then the CIMs would just stand there and wait until they are bored, or wait until it is eg 5am and the first bus arrives.

**Comment by klyte45** [comment]
Actually it was to be already happening. I know it already works when a Cim start to try to find a path, but never checked this situation when they are already in the stop. I will take a look on it soon.
