### ISSUE TITLE
Conflict with vanilla concert (urgent)

### ISSUE THREAD

**Issue by isaac-prog** [klyte45/TransportLinesManager#120]
When this mod is enabled, level 1 and 3 concerts from the concert dlc will conflict with this mod. The GUI of those concerts will rapidly scroll upwards. Urgent fix required as I’m battling with citizen instances in my city

**Comment by klyte45** [comment]
Need more information. Please provide screenshots with what exactly is the issue you are having.
I used to use concert stuff without problems until now.
