### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by eyeaton** [klyte45/TransportLinesManager#131]
When I start creating a new bus line, after the second stop is placed, the game crashes.

**Comment by klyte45** [comment]
I need your log to see what's happening
Look at "Report-a-bug" button to get instructions about how to get it

**Comment by eyeaton** [comment]
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7356039/output_log.txt)

**Comment by eyeaton** [comment]
Thank you for looking at this!

**Comment by klyte45** [comment]
The fix was done. Will be available in the next patch tomorrow.
Thanks for reporting!
