### ISSUE TITLE
Passenger waiting view/line connections/etc view broken, Vehicle Passenger Capacity shown as two fractions

### ISSUE THREAD

**Issue by ILikeFreightTrains** [klyte45/TransportLinesManager#132]
So ever since the new update, the option to choose whether you see how many passengers are waiting at each stop or which stops have connections. Also, the passenger capacity that appears in the minimap is in a X/XX/X form (i.e. a bus with a a capacity of 40 and no passengers on board shows up as 0/4029/30 instead of 0/40).

**Comment by klyte45** [comment]
I can't reproduce it here.. Can you illustrate it with an image and more details about the line itself?

**Comment by ILikeFreightTrains** [comment]
![image](https://user-images.githubusercontent.com/52294724/137599740-ecb51bc0-2494-4021-b3dc-caa2a3c88a93.png)

The messed up vehicle capacity happens to every transport line (except trains, since the passenger count fixed itself today). Every type of transport has the passenger view/connection view/profit view is blank-and there is no drop down menu

**Comment by klyte45** [comment]
Okay, now I need your log
Check the report-a-bug button to get instructions about how to do it

**Comment by varthshenon** [comment]
I'm also encountering this bug (no dropdown menu). Have you found the cause @ILikeFreightTrains ?
I subscribed Real City too.

**Comment by varthshenon** [comment]
![image](https://user-images.githubusercontent.com/7501821/140302817-2f23098e-2fd6-42c1-853e-37946b79d491.png)

**Comment by Kimbons** [comment]
i have the same problem. I was too many time without play cities, i come back i use a old save game and have this problem. I started a new game and TLM works well. I have RealCity, MOM... Did you guys tried a new game?.

**Comment by Kimbons** [comment]
ok, was wrong i said before. Works well on Scneario not in a normal game. I tried new secnario twice and works well, not on new single games. (sorry about my english)

[outputlog](https://ufile.io/doyigphw)

**Comment by ILikeFreightTrains** [comment]
@Kimbons 
1) when you say 'normal game' do you mean a new city or a current city?
2) scenario with or without mods?

**Comment by Kimbons** [comment]
1. new city or loaded city doesn´t matter
2. with mods, that is i mean. the mod works properly on scenarios. at least for me. i mean i have X mods installed. on a "normal game" i have the same issues like you. Now i start a new scenario with the same mods than i have on a "normal game" and the mods works properly.

**Comment by ILikeFreightTrains** [comment]
I did some testing and it seems like Real City is the mod that causes the text to be messed up.

**Comment by klyte45** [comment]
Noted for compatibility issue alert in the future.
I suggest you to talk with PCFantasy to have a fix there. Possibly it's anything with the window binding that being done there and affecting TLM.

**Comment by ILikeFreightTrains** [comment]
Update: For some reason, the passenger count per stop appeared in the minimap in the middle of the game but the dropdown menu is still broken. I'm not sure what happened to make it work again...
