### ISSUE TITLE
This mod causes Asset Manager slowness

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#137]
This has been observed for a long time but then I did not bother to post this. It caused some inconvenience but it is not game breaking.

So I found that, if I enable this mod in the Asset manager, then if I later enable/disable any other asset I will need to wait a few seconds, which does not happen if I do not enable this mod.

For example:

1. Enable this mod
2. Enable some other mod
3. Need to wait a few secs (<- does not happen if this mod is disabled)
4. The other mod is enabled, that mod can run with no problems

It is very strange, so maybe there is something happening in the background?

**Comment by klyte45** [comment]
This happens because of code patching plus translation system reloading. This happens with any of my mods (and with some from other modders too)

Once it only happens in activation/deactivation time, I'm not planning to review it by now.
