### ISSUE TITLE
Suggestion: UI allows fine adjustment of values

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#138]
The transport line UI is very important to this mod, and I have a suggestion.

There is a common UI element that is the bar. We use the bar to adjust various values of the transport line, eg:

- Service %; it can allow a value jump of 5%, or perhaps 1 vehicle in the "show absolute vehicle count"
- Fare; it can allow fare to adjust by $0.05

Usually what happens for me is that I want to set the fare to eg $2 but usually I can only click it to be $2.05 or $2.10, and then it is very difficult to use the mouse to drag the bar back to $2. When I drag the bar, it overshoots to e.g. $1.95, and then I drag it back and then it goes back to $2.10. Very difficult to get to $2.00, but not impossible because when I try really hard with a slow mouse speed, I can really go to $2.00.

(I am using Dynamic Resolution to change the resolution to 50% so that I can play the game smoother, does this affect how the bar works?)

What I suggest is to somehow follow the base game's feature, allow users to use the mouse scroll on the bar to fine tune the values. As an example in the base game, if you go to the base game options menu, you can use the mouse scroll to adjust eg the music volume.

**Comment by klyte45** [comment]
Actually, I'm planning already to make the display label editable. So you will be able to type any value.
This solution will solve other problems, like when you want to use values out of range of the scale.
