### ISSUE TITLE
Add and select vehicles + window lock

### ISSUE THREAD

**Issue by StayHungryStayFoolish2021** [klyte45/TransportLinesManager#142]
After subscribing to Transport Lines Manager 14.1 and unsubscribing from the Improved Public Transport 2 all buses were gone. I would set up the budget, but I did not know which line is which one. The budgeting logic is strange, I would just increase the number of buses from zero. The window cannot be moved, and it is behind the vanilla menu. Please advise.

**Comment by klyte45** [comment]
I won't doubt the MOM may be the root cause of this issue, just writing for the other people that may reach here later with a similar issue. I had no time to check it deeply and the lack of information with logs also doesn't help.

So, closing by inactivity.
