### ISSUE TITLE
Crash when making bus line

### ISSUE THREAD

**Issue by SifVerT** [klyte45/TransportLinesManager#143]
Hi,

Thanks for this mod which truly enhances the public transport functionality, but now I've run into some kind of strange bug which only happens for buses and when placing bus line nodes (stops) and the game only crashes if I place them while the game is unpaused, if I pause the game I can lay down the bus line properly and start the buses. I can use the mod for buses if I remember to pause the game each time I'm to make a new bus line but it gets frustrating. Tried for hours today, removed all other mods than yours and another save etc.

Note that an old save I have works fine and I can add bus lines without the game crashing while the game is unpaused.

Sending the log for three different crashes with the same outcome i.e. crash to desktop.

Many thanks again for your mod, I like it.

[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7365939/output_log.txt)
[output_log2.txt](https://github.com/klyte45/TransportLinesManager/files/7365940/output_log2.txt)
e
![crash](https://user-images.githubusercontent.com/49654661/137754651-17742439-78be-4308-b6e6-23fddc064bcc.png)
[output_log3.txt](https://github.com/klyte45/TransportLinesManager/files/7366005/output_log3.txt)
.

**Comment by klyte45** [comment]
> Can you try the new [alpha version?](https://github.com/klyte45/TransportLinesManager/tree/alpha/_requiredDLLs) Just copy this files in your local APPDATA Cities Skylines folder under path: `Addons/Mods/TLM` Let me know if need help to test it. Don't forget to turn off the workshop version of the mod (may unsubscribe)

A new alpha version was release. Please try it when possible. I found a lot of possible causes of the crash issues.

**Comment by SkillzGamingYT** [comment]
@klyte45 
Have you updated the mod with the fixes with crashing after making lines?

I tried the alpha channel, it still crashes and the in-game menu says it's 14.1still:
![image](https://user-images.githubusercontent.com/26197169/139794421-5ab9097f-1c85-4fc0-bee0-2cb0b0e54629.png)

**Comment by WILL07555** [comment]
Hi I have the alpha version and it still crashed the game until i paused the game first then added 3 bus routes which didn't crash the game and then i could make bus routes with the pause off, not sure why this happened but it was the way i could get past the crashes and it was only bus lines nothing else.

I hope this helps

**Comment by klyte45** [comment]
Hi people
The 14.2 version was delayed to later January to also bring fixes for the new DLC announced this week. Due the game code has changed, it's unlike to be available a new alpha version until there. Thanks for your patience.
