### ISSUE TITLE
Cross-thread calls

### ISSUE THREAD

**Issue by krzychu124** [klyte45/TransportLinesManager#149]
Like we've talked via discord there might be an issue with cross-thread calls resulting in hard to find bugs when simulation is running.

I've created little tool, covered public methods of `VehicleManager` and `CitizenManger` which vanilla always call from simulation thread.  Once incorrect use occur then you will see an error dialog and the action will be suppressed (throwing an exception might be a better solution? - mod author probably does not expect it there so it will be guaranteed to stop execution completely)

Anyways, for now (limited time on my side) it's just a small tool to make sure that most important parts of the mod won't cause any unintended problems. 

[InvalidOperationDetector_v1_0-alpha1.zip](https://github.com/klyte45/TransportLinesManager/files/7384106/InvalidOperationDetector_v1_0-alpha1.zip)

**Comment by klyte45** [comment]
FYI, this fix will be released along the patch update for the incoming Airports DLC in late January

**Comment by krzychu124** [comment]
Great!

**Comment by klyte45** [comment]
Well, due another urgent issue needed to be fixed, the update is already live in TLM!
