### ISSUE TITLE
Added next ko.properties version

### ISSUE THREAD

**Issue by ToothlessFLY-LShst** [klyte45/TransportLinesManager#15]
I try 8 time pull requests. not work and 404 error T.T
i think server problem.

anyway, new version here!
https://gist.github.com/ToothlessFLY-LShst/ebb0e2edc73109b3a97bb14387c2c789

**Comment by weoiss1998** [comment]
I created a pull request

**Comment by ToothlessFLY-LShst** [comment]
thank you!

**Comment by klyte45** [comment]
Both files merged. Thanks guys!
