### ISSUE TITLE
Re: Train assets with AVO "allow this vehicle to spawn" disabled cannot be selected

### ISSUE THREAD

**Issue by kenty-CSL** [klyte45/TransportLinesManager#150]
https://github.com/klyte45/TransportLinesManager/issues/110
The last update of avo is 2021/06/13. However, this problem had occurred before this day.
I said that this issue started in April, but I think it actually occurred from the 2021/03/24 or 2021/03/21 update.
Please investigate again.

**Comment by flyrobot27** [comment]
Do we have a rough ETA on when 14.2 would be released?

**Comment by klyte45** [comment]
Yep, it will be released along the new Airport DLC coming to the game in late January.

**Comment by klyte45** [comment]
It's now available already. Check it out.
