### ISSUE TITLE
Editing capacity of taxicabs not possible

### ISSUE THREAD

**Issue by CrankyAnt** [klyte45/TransportLinesManager#152]
All capacities of transit verhicles can be edited through their respective line overviews, however there is none for taxi's as they are selfsufficient. In AVO the default capacity is 4, but TLM overwrites this with 10.. 
10 people do not fit in a regular car so I would like to change that; could you lift the override pls?

**Comment by klyte45** [comment]
Wait, that counter of taxis is about the trip counter for current work shift, not the taxi capacity, once it's only one person at time getting loaded and unloaded. So, this makes no sense...
