### ISSUE TITLE
Issue when I delete and create lines

### ISSUE THREAD

**Issue by bornatoviski** [klyte45/TransportLinesManager#154]
When I delete one line and create a new the new line don't shows no one information and is on red alert.

![Captura de tela 2021-10-27 193454_LI](https://user-images.githubusercontent.com/90569865/139157544-8948aa28-0fdd-4375-b8b1-8e468d3d8917.jpg)

**Comment by RundeKatze** [comment]
Have the same problem. I delete one line and many others disappear. When I create one it did not even show up. When I want to open the line details the game freezes forever but it does not crash. In my case it appears with Metro lines.

**Comment by klyte45** [comment]
This issue will be addressed in the next update for the new DLC, in later January. Until there I suggest to delete only by the line detail screen to avoid this red line.

**Comment by klyte45** [comment]
The update was done today
