### ISSUE TITLE
Conflict with the Improved Public Transport 2 mod

### ISSUE THREAD

**Issue by EpiccraftTV** [klyte45/TransportLinesManager#156]
When I load the game with both mods enabled, the TLM mod tells me that I should disable Improved Public Transport 2 because of conflicts. Running both mods together also causes the game to lag out heavily. It would be nice to see the two mods be compatible or at the least have the vehicle and stop windows from IPT2.

Edit: Clarifying and simplifying what I meant in the last bit.

**Comment by klyte45** [comment]
Hi! 
It's impossible right now. IPT2 and TLM are very different by this time. The last version compatible was available something like 4 years ago!

So sorry but it won't be done.
