### ISSUE TITLE
Freeze when changing language

### ISSUE THREAD

**Issue by Horusbk** [klyte45/TransportLinesManager#158]
Hello,

When I change the language of the mod (Transport Manager), the game freezes.
![image](https://user-images.githubusercontent.com/54979157/141282067-0697cf90-4ecc-49ba-865a-af2ba382b63b.png)

**Comment by klyte45** [comment]
Unfortunately this is a known issue without solution and many modders have this issue in their mods. The mitigation for it is to wait the game to unfreeze (may take few minutes) or just restart the game during the freeze and check the locale applied after it.

**Comment by Horusbk** [comment]
Thanks Klyte!
