### ISSUE TITLE
When adding a line and game is unpaused, game freezes

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#160]
Haven't played C:S while. Found a bug that when I had running and I started placing line, right around second stop placement game freezes. This happens every time if the game is running. If the game is paused the issue does not occur,.

Did a lot of testing and mod disabling and I found the culpurit to be TLM. If I disable TLM and keep all other mods, everything works.

If I only kept TLM, Load Order Mod and Loading Screen mod enabled, this issue appears.

No errors appear in output_log.txt

**Comment by EpiccraftTV** [comment]
Yea, this has been happening to me as well. I've had plenty of times where I forget to pause the game and loose about 5 minutes or so of work because I have to force close the game.

**Comment by GameBurrow** [comment]
Seems related to https://github.com/klyte45/TransportLinesManager/issues/146 ?

**Comment by klyte45** [comment]
Yep, it's being discussed now at #143, since it's the same issue.
The fix might be available at Airport DLC Patch in January.
