### ISSUE TITLE
Unified UI Support

### ISSUE THREAD

**Issue by EpiccraftTV** [klyte45/TransportLinesManager#161]
Have support for UUI would be very nice as it would help clean up the screen. Also the ability to move the line viewer window would be absolutely wonderful and would make things a lot easier when trying to use it and view the route in the city itself.

Also, for some reason I'm not able to scroll in the line viewer window and the routes aren't being sorted properly, I have route 3 that shows up below route 13, which shouldn't be the case. The names of the routes start with the numbers, e.g. "13 - <name>".

**Comment by klyte45** [comment]
Probably you having an line corrupted in some way, or it's a bug in TLM that will be released a fix in next patch.

About the UUI, I will check the possibility to do it in next patch.

**Comment by klyte45** [comment]
The Unified UI support will be available in next version, in late January:
![image](https://user-images.githubusercontent.com/11671356/145702489-84c6c24a-c4f8-4732-9801-cc3fa80e3851.png)
