### ISSUE TITLE
Setting exact line colours via hexadecimal codes no longer possible

### ISSUE THREAD

**Issue by LuMaRainbow** [klyte45/TransportLinesManager#163]
One of my most beloved features of TLM was setting exact line colours via hexadecimal code. I created a list with colours I wanted to use, but the text field to add hex codes no longer shows up, neither in the line overview window nor in the settings window for individual lines. I tried using a colour pallette instead, but that still doesn't work. The mod recognises my pallette just fine, but won't adjust the colours when clicking the button, even though I set the line number accordingly.

Was this an intentional change or is it maybe a conflict with another mod? I'm using a lot of different mods, but none of those conflict with TLM according to the Auto Repair Mod... Hopefully I'm soon able again to set my exact line colours :)

**Comment by klyte45** [comment]
Well, it wasn't intentional. I will check it to try to add it again in the next patch in late January.

**Comment by klyte45** [comment]
It's done and better than before:
![image](https://user-images.githubusercontent.com/11671356/145924410-d26cb110-841f-47ce-8a71-47aee11fa253.png)
Will be available in 14.2, the Airports DLC update
