### ISSUE TITLE
Draggable main window

### ISSUE THREAD

**Issue by wind-of-changes** [klyte45/TransportLinesManager#164]
Please Make a draggable windows or else it is a problem because they are very big and cover almost the whole screen.

**Comment by klyte45** [comment]
It's already possible by using Ctrl+click in <K> button
But if you have another mod from me there that didn't received an update recently, may not work. It will be reviewed for v14.2 in January.

**Comment by klyte45** [comment]
The Unified UI support will allow the window to be moved freely. Check it at #161 for details
