### ISSUE TITLE
TLM View VS PT-LO

### ISSUE THREAD

**Issue by shadertheboi** [klyte45/TransportLinesManager#165]
![image](https://user-images.githubusercontent.com/59530097/145669391-3c85a50a-59ee-46ea-9c27-f2776dcbeef6.png)
Any idea what is going on in the PT-LO screen? I accessed this screen via AVO by clicking on the "Manage Spawning in Transport Line Overview".

**Comment by klyte45** [comment]
Default PT-LO is not meant to be accessible with TLM. For now I advise to use the TLM screen and avoid the AVO shortcut while a definitive solution isn't designed.

**Comment by shadertheboi** [comment]
Noted. Thanks Klyte!
