### ISSUE TITLE
Bypass Stop/Station based on Time of Day

### ISSUE THREAD

**Issue by yasinallahdev** [klyte45/TransportLinesManager#173]
With the express service being a feature for buses, trams, and trolleybuses, and certain stops being able to be marked as terminals, would it be possible to mark stops to be able to be bypassed based on time of day (for example, trains will not stop at stations exclusively serving school districts at night, but will service all other stations on the line)?

I don't think it would be the simplest feature to implement, and it also feels very specific I will admit, but I thought I'd float the idea around.

**Comment by klyte45** [comment]
For this feature, I suggest you to create 2 lines: an express and another full. Then make them available only some time in the day by setting the budget to zero when it wouldn't be working. It's available at this screen:
![image](https://user-images.githubusercontent.com/11671356/146507459-31077d16-539b-4251-86df-dbd0590096ae.png)
