### ISSUE TITLE
The game freezes while creating a bus line. TLM14.2

### ISSUE THREAD

**Issue by Trove226** [klyte45/TransportLinesManager#176]
After the current update, I have repeatedly found that when the 2nd or 3rd stop is selected when building a bus line (selection), the game freezes. The music will still play for 10-15 seconds, but the game will not close to ALT-F4, the task manager will not appear with CTRL-ALT-DEL. Only the PC can be reset.
There was no problem with the subway and train. I haven't tried the rest yet.

**Comment by klyte45** [comment]
I need your log generated after it happened to check it deeply
See Report-a-bug helper to get more information

**Comment by m3shat** [comment]
I have the same problem (but don't need to hard reset my PC, windows will recover). I do have a lot of mods and (broken) assets tho so it might not be easy to find the relevant parts in my log

[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7900941/output_log.txt)

Issue is exclusively with bus stops and does not happen immediately but after a few seconds after placing the first stop.

**Comment by klyte45** [comment]
Wait for the 14.3 on tuesday, it might be fixed
If not please report it again with a new log

**Comment by klyte45** [comment]
It was caused by NodeController mod.
See at line 19902 of the log:
```
0x00000000A2308821 (Mono JIT Code) NodeController.Patches.NetSegmentPatches:CalculateCornerPrefix (NetInfo,NetInfo,uint16,uint16,bool,bool,UnityEngine.Vector3&,UnityEngine.Vector3&,bool&)```

Please issue this at their repository: https://github.com/MacSergey/NodeController30
