### ISSUE TITLE
The game freezes after making a train line

### ISSUE THREAD

**Issue by wkwkwkwk12345** [klyte45/TransportLinesManager#184]
Hi, I was making a train line, after it's done, i go to the mod menu and take a look at my new line, suddenly, the game freezes and not responding.

**Comment by klyte45** [comment]
I need your log. Get it at Report-a-Bug helper button at mod pause menu  options

**Comment by wkwkwkwk12345** [comment]
The game is literally freezed and there's no way how to get the log while in game, if I alt+F4 it because as i explained before, still could I get the log? But I'll try it anyway

**Comment by klyte45** [comment]
So read the tutorial first, do the stuff to get the issue logged, then you do what you read firstly to get the log file and send it to me

**Comment by wkwkwkwk12345** [comment]
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7808140/output_log.txt)
Is this the log you asked for? i found this on Cities_Data

**Comment by wkwkwkwk12345** [comment]
oh yeah this also happened when im click on "Line Details"

<img width="960" alt="Screenshot 2022-01-04 211250" src="https://user-images.githubusercontent.com/72007455/148071832-9fe51a28-ac50-4ac3-b262-bd8ffd6d1d5f.png">
)

**Comment by klyte45** [comment]
I noted that you seems to not be using an official version of the game. So there's no stuff to do from my side.
