### ISSUE TITLE
[FEATURE] Option to adjust the operational hours of a certain line

### ISSUE THREAD

**Issue by Transportation-master-kcl** [klyte45/TransportLinesManager#187]
I found that most passengers tend to concentrate on certain parts of a route, especially during peak hours. Therefore, I set up local routes that only go between busy stations. Those lines are, however, only useful during peak hours.

The day/night only lines in the vanilla game seems to be missing when TLM is enabled. How to solve this?

**Comment by YuLun-bili** [comment]
TLM already have the feature of adjusting budget by time. If you open 'Line Details' window, the third option panel is 'Budget Settings'. [https://steamuserimages-a.akamaihd.net/ugc/768360864911523703/5B214A7870DF4346EC8578A108DBED4BAE06048D/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false](Here's a screenshot)
