### ISSUE TITLE
Update Korean plz

### ISSUE THREAD

**Issue by ToothlessFLY-LShst** [klyte45/TransportLinesManager#19]
i don't know
why not work only TLM Pull request.
other cities skyline mod github Pull request good work.
but i try upload TransportLinesManager/UI/i18n/ko.properties,
404 error

anyway new version here.
and i can't find 'Line's Multiplier'. So i all done except 209 / BUDGET_MULTIPLIER_TITLE_LINE=Line's Multiplier\n{0} ({1}).

https://gist.github.com/ToothlessFLY-LShst/ebb0e2edc73109b3a97bb14387c2c789

**Comment by ToothlessFLY-LShst** [comment]
@klyte45 =D

**Comment by klyte45** [comment]
Added for 7.1

**Comment by klyte45** [comment]
Try to create another fork to make changes directly at the project
