### ISSUE TITLE
[BUG] Crash when clicking Metropolitan Airport

### ISSUE THREAD

**Issue by Chiefwei** [klyte45/TransportLinesManager#190]
**Describe the bug**
The game crashes when I build and click Metropolitan Airport, but other airports (like International Airport) work fine.

**To Reproduce**
1. Build a Metropolitan Airport.
2. Click it.
3. The game crashes.

**Game Logs**
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7834516/output_log.txt)

**Comment by klyte45** [comment]
This situation is solved and will be released in the next release in January 25th
