### ISSUE TITLE
[FEATURE] I think the bus can stop at the terminal longer

### ISSUE THREAD

**Issue by PC28K** [klyte45/TransportLinesManager#191]
With the use of the express function, it did not stop at the intermediate stop or adjust the vehicle interval. 
However, the time stopped at the terminal stop to adjust the vehicle interval is too short, and vehicles do not seem to be distributed in a balanced manner on routes with fewer vehicles.
I don't know much about the CSL and mod, so I can't say for sure, but I think this problem arises because the time required to adjust the vehicle spacing is longer than the maximum time the vehicle can stop.

I want to stop at the terminal stop for a longer time and leave after the distance from the car in front is sufficiently secured. 
For example, if two vehicles operate on a route with eight stops, the next car must depart from the first stop when the car in front is at the fourth stop. (Suppose that the distance between stops is constant.)

The "interval acceleration factor" in the IPT seems to function similar to that. (When I used to use IPT in the past, I used it.)
The function of the IPT seems to be a function of setting the maximum time for the vehicle to stop at the stop to adjust the interval. I used it to more than double the default value for accurate spacing.
If similar functions are provided in TLM, it seems that the problem can be solved.

Now on two vehicles and eight stops bus line, when the vehicle ahead is at the second stop, the next vehicle departs. 
When express is not used, stop at several stops and adjust the dispatch interval, but if express is used, it is impossible.
so, i want to provide sufficient stopping time so that we can secure sufficient interval at the first stop.

**Comment by klyte45** [comment]
Seems feasible to be done, but it will require some study time

I'll get back on this later

**Comment by PC28K** [comment]
okay thanks!

**Comment by praveenjabakar** [comment]
https://github.com/klyte45/TransportLinesManager/issues/206#issuecomment-1028160401

More like same issue

**Comment by klyte45** [comment]
Once #206 have a richer discussion about this issue, this matter will be treated there
