### ISSUE TITLE
[BUG] Button cannot be moved

### ISSUE THREAD

**Issue by MatthewForrester** [klyte45/TransportLinesManager#194]
**Describe the bug**
The  button for the TLM Menu cannot be moved.

**To Reproduce**
1. Subscribe to TLM 14.2 in Steam and enable it in the C:S Content Menu.
2. Load a game.
3. Hover over the 'K' button in the top-left-corner. It says "Ctrl+click to move the button!"
4. `CTRL+CLICK` on the K icon.

**Expected behaviour**
The button can be dragged to another place on the screen.

**Actual behaviour**
The TLM Menu (TLM Line Overview) opens.
If you `CTRL+CLICK→DRAG` then nothing happens.

**Game Logs**
- [Player.log](https://github.com/klyte45/TransportLinesManager/files/7919152/Player.log). The most useful part appears to be this:
 ```
Steam ID: 255710 [Message]
The following assembly referenced from data-0x6decc20 could not be loaded:
     Assembly:   UnifiedUILib    (assemblyref_index=9)
     Version:    2.1.12.29784
     Public Key: (none)
The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (/home/linmanfu/.steam/debian-installation/steamapps/common/).

Could not load file or assembly 'UnifiedUILib, Version=2.1.12.29784, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
The class <>c__6`3 could not be loaded, used in TransportLinesManager, Version=14.2.0.9, Culture=neutral, PublicKeyToken=null
```
  - Maybe this part of TLM has a hidden dependency on UnifiedUI?
- [CompatibilityReport.txt](https://github.com/klyte45/TransportLinesManager/files/7919151/CompatibilityReport.txt)

**Screenshots**
![Screenshot of the button's current location](https://i.imgur.com/lTIJQMD.png)

**Additional context**
I am using the Steam version of C:S, running as native on Linux (Ubuntu 20.4 LTS).

**Comment by MatthewForrester** [comment]
If I subscribe to and enable the Unified UI mod, then I enable to move the button and the TLM Menu.

**Comment by klyte45** [comment]
The ctrl+click feature will be obsolete soon. Unified UI seems to be the future of <K> button, then it will become a dependency of it.

With this design choice done, this bug is obsolete too.
