### ISSUE TITLE
[FYI] TLM is incompatible with the Commuter Destination mod

### ISSUE THREAD

**Issue by MatthewForrester** [klyte45/TransportLinesManager#195]
**Describe the bug**
TLM is incompatible with the Commuter Destination mod.
(This is not exactly a bug with TLM and I realize that TLM cannot be compatible with every mod. You already work so hard on so many mods! But the bug report is a clear way to describe the problem to you (kyte45] and the Compatibility Report team.)

**To Reproduce**
1. Subscribe to, and enable, TLM and the Compatibility Report mod.
2. Create a game with transport lines and save it.
3. Subscribe to, and enable, [the Commuter Destination mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2475986859&searchtext=commuter+destinations).
4. View the Compatibility Report.
5.  Load the game from step 2.
6. Open TLM Menu (Lines Overview).
7. Open a line.
8. Click on a stop.
9. Close and re-open TLM Menu.
10. Open a line.

**Expected Behaviour**
At step 8, Commuter Destination displays commuter destinations. At step 10, TLM works correctly.
Or the [Compatibility Report](https://steamcommunity.com/sharedfiles/filedetails/?id=2633433869) warns about the problem. I have used this page to inform the Compatibility Report team.

**Actual Behaviour**
At step 8, Commuter Destination displays commuter destinations, but the game pauses and cannot be unpaused.
At step 10, TLM says "Line incomplete" and has multiple errors (incorrect data, overwritten text, and the first tab is duplicated).

**Game Logs**
- [Commuter Destinations and TLM Bugged Player.log](https://github.com/klyte45/TransportLinesManager/files/7920376/Commuter.Destinations.and.TLM.Bugged.Player.log)
- [Player.log of Commuter Destinations without TLM for comparison](https://github.com/klyte45/TransportLinesManager/files/7920374/Player.log)
- [CompatibilityReport.txt](https://github.com/klyte45/TransportLinesManager/files/7920450/CompatibilityReport.txt)

**Screenshots**
![Screenshot of TLM with graphical errors at step 10.](https://user-images.githubusercontent.com/38819845/150676888-45374b7c-2b8c-47ef-8ff8-d3bb1855eb19.png)

**Additional context**
I am using the Steam version of C:S, running as native on Linux (Ubuntu 20.4 LTS).

**Comment by Finwickle** [comment]
This incompatibility will be mentioned in Compatibility Report with the next catalog (somewhere in the next few days).

Have you mentioned this to the Commuter Destination mod creator? Otherwise you might want to create an issue there as well: https://github.com/Jameskmonger/CSL-ShowCommuterDestination/issues

**Comment by Jameskmonger** [comment]
Thanks for reporting this. I currently have a new version of Commuter Destination in development, I will investigate to see if the same happens there and prioritise the release if it's fixed.

**Comment by MatthewForrester** [comment]
@Finwickle You are right, I should have reported it over there too. Thank you for responding on your part.

**Comment by klyte45** [comment]
Well, it was tested in TLM 14.2
Please check this at TLM 14.3. It might not be a incompatibility issue at all.

**Comment by Finwickle** [comment]
Any news on this?

**Comment by klyte45** [comment]
I was busy with real life and other mods, getting back on this soon!

**Comment by klyte45** [comment]
Well, 2 important things:

1) Commuter Destination Mod wasn't updated for Airports, and seems broken
2) It seems that something in that mod is preventing the Line ID field from vanilla field to be read. So TLM got always 65535 as a line ID, which is invalid

I believe you would need to contact the mod developer to check these points, and if necessary to work together to add support of it here, or in worst case, to include this feature in TLM

Closing by now (may be reopened with news)
