### ISSUE TITLE
[BUG] The info boxes does not display properly 

### ISSUE THREAD

**Issue by sinair285** [klyte45/TransportLinesManager#199]
**Describe the bug**
The info boxes does not display properly and cannot be used

**To Reproduce**
Just click any of the info boxes related and error occurs

**Game Logs**
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7933726/output_log.txt)

**Screenshots**
![image01](https://user-images.githubusercontent.com/98399437/150981468-53a5ab9f-743e-46b0-959c-8c10fad313af.png)

**Additional context**
Tried to remove all other mods from the game but problem presist.

**Comment by rogonion** [comment]
I got a similar issue too while in-game whereby the UI is messed up and unresponsive. In addition, when I activate the mod while on the main menu, I get the below error prompts:
![Screenshot 2022-01-25 171621](https://user-images.githubusercontent.com/40334795/150997646-9bc54b6e-0c25-43b5-8d2f-ea38f593f326.png)
![Screenshot 2022-01-25 171755](https://user-images.githubusercontent.com/40334795/150997662-6c93433c-40d5-40c5-b289-d6bf3cac8c2b.png)
Output log is here [output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7934446/output_log.txt)

**Comment by ShinyMooTank** [comment]
I'm also having UI alignment issues and all my Lines saying they are incomplete in the UI.

**Comment by gitblogger** [comment]
I've got a similar issue. [Here is what it looks like in-game.](https://steamcommunity.com/sharedfiles/filedetails/?id=2731523682)

**Comment by ShinyMooTank** [comment]
It's something with Steam workshop and Transport Lines Manger not pushing out the update. I have Resubscribed to the mod, and it doesn't fix it and it's stuck on the Jan 3rd update from 3 weeks ago.
https://twitter.com/Klyte45/status/1485991111843880978?s=20

**Comment by ShinyMooTank** [comment]
https://twitter.com/Klyte45/status/1486068597273288704

**Comment by bennettJH** [comment]
Hi all, sry to bother, but I am having the exact same issue here and I have subscribed the new version (14.3) days ago. Are you still experiencing the issue and do you have any suggestions? Thx!
