### ISSUE TITLE
[BUG] No income/expenses breakdown for newer created lines

### ISSUE THREAD

**Issue by TMaekler** [klyte45/TransportLinesManager#213]
**Describe the bug**
For the newer created lines it looks like the weekly income/expenses breakdown for busses have stopped working. They work fine for the older lines, but not the newer ones. See screenshot.

**Screenshots**
https://ibb.co/WnS1tbF

**Comment by klyte45** [comment]
It's not a bug.
The value in the list is from the last FULL BILLING PERIOD. Once the line is new, there's no budget in the last accounting period, then the value will be zeroed until the line complete a period.
