### ISSUE TITLE
Some Buses from Vehicles of the World pack are missing in the selection list 

### ISSUE THREAD

**Issue by GrzegorzLep** [klyte45/TransportLinesManager#216]
I found that I can only select 2 of the 4 buses from the Vehicles of the World pack. The Articulated bus and the double-deck England style are absent from the list. If I leave it at a random, all the buses will show on the road bat, not in the selection list.

**Comment by klyte45** [comment]
I believe it might be something from older version, because both are listed today
![image](https://user-images.githubusercontent.com/11671356/160203120-496d7cb9-7bc0-4210-b72e-f637a6ee3fce.png)
Closing issue
