### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Toppok** [klyte45/TransportLinesManager#220]
**Describe the bug**

The Mod C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\1312767991 [0Harmony.dll, TransportLinesManager.dll] has caused an error [ModException]

Details:
System.TypeLoadException: Could not load type 'UnifiedUI.Helpers.UUIHotKeys' from assembly 'TransportLinesManager'.
at Klyte.Commons.Interfaces.BasicIUserMod`3.OnLevelLoadedInherit (ICities.LoadMode) <0x001c5>
at Klyte.Commons.Interfaces.BasicIUserModSimplified`2.OnLevelLoaded (ICities.LoadMode) <0x00029>
at (wrapper dynamic-method) LoadingWrapper.LoadingWrapper.OnLevelLoaded_Patch4 (LoadingWrapper,SimulationManager/UpdateMode) <0x000b9>

**To Reproduce**
1. Continuing or loading an existing savegame
2. nothing more done

**Game Logs**
first is continuing autosave
secong is a savegame

kind regards
Klaus

[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/8102868/output_log.txt)
[output_log second try.txt](https://github.com/klyte45/TransportLinesManager/files/8102870/output_log.second.try.txt)

**Comment by Grimpac** [comment]
Got the same error. I disabled "Use Unified UI" in the MOD options. It didn't work for me after all, even though I had no use for it, so it is OK now.
![image](https://user-images.githubusercontent.com/100052373/154823370-0e69a82f-332c-4060-b924-82b9447e8220.png)

**Comment by Toppok** [comment]
Thank you @Grimpac 
this worked for me as well.

**Comment by michellereth** [comment]
Thank you this worked @Grimpac

**Comment by klyte45** [comment]
Well, this issue is related to someone else that uses natively the Unified UI mod. Kian is aware and working in a fix
For now, the solution is disable it as @Grimpac  mentioned.
