### ISSUE TITLE
[BUG] Broken UI screen again

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#221]
**Describe the bug**
While previously fixed, the UI screen for bus line profits is broken again: cells are misaligned.

**Screenshots**
![Screenshot (223)](https://user-images.githubusercontent.com/17726797/154837941-c9b95401-4f70-4621-93b7-88dd4709074e.png)

**Comment by klyte45** [comment]
Marking as Won't Fix, because the UI of TLM will be full rebuilt soon, in the path of Prop Switcher, Vehicle Skins and Write The Signs model 
So this issue certainly won't happen anymore after it😜
