### ISSUE TITLE
[BUG] Overflowing line details toggle button

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#231]
**Describe the bug**
In the budget screen, clicking on the area in yellow can affect the state of the toggle, but this is quite unexpected. So far, this is the only button that has this overflow problem.

**Screenshots**
<img width="342" alt="Screenshot" src="https://user-images.githubusercontent.com/17726797/157461487-33788d51-6162-4150-acad-f4b883503ea7.png">

**Comment by klyte45** [comment]
Won't be fixed due the new UI planned for TLM
