### ISSUE TITLE
TLM 14.3 regional platform settings window blocked.

### ISSUE THREAD

**Issue by nuyorkah** [klyte45/TransportLinesManager#232]
When clicking on any vanilla or workshop Train Station the pop-up window to select platforms is blocked by Intercity Types window.
Is there a way to reposition these windows?

1. Go to any train station.
2. Click on the TLM platform settings.

![Screenshot 1](https://user-images.githubusercontent.com/101583485/158217403-048fcdb7-e30f-469c-9cc7-3a97dbceb496.png)

![Screenshot 2](https://user-images.githubusercontent.com/101583485/158217466-e75371ad-b8da-4652-a028-49c0598df535.png)

Thanks for your mods!

**Comment by Vectorial1024** [comment]
On another resolution (1600x900), the same button blocks the routes view:

<img width="801" alt="Screenshot (284)" src="https://user-images.githubusercontent.com/17726797/158635062-cadaf53a-8c87-4e9b-97c5-1255eba63d03.png">

The routes view is behind the TLM UI instead.

**Comment by klyte45** [comment]
This will be solved in the new TLM UI planned for 15.0, so no fix by now.
