### ISSUE TITLE
[BUG] Play It! conflict with financial reports

### ISSUE THREAD

**Issue by Ruefren** [klyte45/TransportLinesManager#235]
**Describe the bug**
When the day/night cycle is on, but the Day/Night Speed is paused in Play It! the financial reports do not save the week's results. Instead all activity accumulates in the current week.

**To Reproduce**
1. Enable Day/Night cycle.
2. Move the Day/Night speed of Play It! to paused.
![image](https://user-images.githubusercontent.com/101930883/159121143-7493bac4-c081-4be0-87b2-fac92e557427.png)

3. Run the simulation for at least 7 days and see that the financial reports are not functioning properly.
4. Turn Day/Night cycle off and run for at least 7 days and see that it starts working again.

**Screenshots**
The week with -61010 was the result of turning day/night cycle off.
![image](https://user-images.githubusercontent.com/101930883/159121010-a41cbc2b-7e01-4d74-9b9a-c1f9a91ef5eb.png)

When day/night cycle is on the quick summary also shows 0.
![image](https://user-images.githubusercontent.com/101930883/159121198-a7839841-3179-49f5-8b30-97fcb66499c9.png)

**Additional context**
Not game breaking, just have to remember to turn day night cycle off rather than pause with Play It! if I want daylight for building.
Possible solution would be to have an option that forces use of the game clock rather than only if the day/night cycle is paused?

**Comment by klyte45** [comment]
I won't fix that because, for me, Play It! might disable the day/night the game in vanilla way to prevent this and other mods that get based in day/night cycle to work properly
