### ISSUE TITLE
[FEATURE] Timetabled Buses

### ISSUE THREAD

**Issue by A121314151** [klyte45/TransportLinesManager#238]
Hello there,

I think it'll be interesting if timetabled buses are implemented for more realism. If you're not planning on adding it yourself, could I request to help out by writing the code for it? I'm quite great with Java and I can use those skills onto C#.

Best Regards,
Qizhe

**Comment by klyte45** [comment]
The timetable feature itself is very hard to implement due the variety of ways you can play the game (with/without day/night cycle and also with the real time). But an improved control of departures is planned for future versions with something near a timetable, but without direct relation with game time - setting it by interval between vehicles in terminal stops.

It's being discussed/implemented under #206. So closing this.

**Comment by A121314151** [comment]
It's alright, what if I help to develop it so that it solely works with
Real Time (essentially, if you do not have the mod, the timetable feature
doesn't really work)?

**Comment by A121314151** [comment]
> The timetable feature itself is very hard to implement due the variety of ways you can play the game (with/without day/night cycle and also with the real time). But an improved control of departures is planned for future versions with something near a timetable, but without direct relation with game time - setting it by interval between vehicles in terminal stops.
> 
> It's being discussed/implemented under #206. So closing this.

Possibly I was thinking to help with the code and adding an additional layer to enable it to work with game time only if Real Time is enabled, essentially eliminating the problem with it and if real time is disabled, it could possibly be off and replaced with the default layer. Personally, my 2¢
