### ISSUE TITLE
Bus abnormality

### ISSUE THREAD

**Issue by Xsz2856** [klyte45/TransportLinesManager#239]
The number of vehicles on my bus line is 0. Even if the budget is adjusted to 500%, it is 0. Other public transport modes are normal, only buses are abnormal.

**Comment by prosectura2** [comment]
I experince the same, no buses spawn at all.

**Comment by freeman** [comment]
Check that you have the standard bus depot, not the biofuel one. This fixed it for me.

**Comment by CraziFuzzy** [comment]
@freeman Thank you, that worked instantly for me - added a standard bus depot and the line numbers started climbing up.  Would love to get this escalated, as this does seem to at least identify the condition rather easily.

**Comment by klyte45** [comment]
Well, if you wanted to non-biofuel buses to be spawn in a biofuel depot, should mark it explicitly at depot selection list. Otherwise, the vanilla rules for spawn will be followed.
