### ISSUE TITLE
Game keeps crashing when moving/adding/removing bus stops

### ISSUE THREAD

**Issue by kerts93** [klyte45/TransportLinesManager#24]
I keep crashing (not everytime), when I do following with bus stops:

- moving

- adding

- removing

Including my logfile also that resulted in game turning unresponsive and crashing. Also looking at the log, has some dev function stayed on that the log is spammed full with TLM lines?
[output_log.zip](https://github.com/klyte45/TransportLinesManager/files/1800621/output_log.zip)

**Comment by klyte45** [comment]
It's because of a bug in debug option log. It's turned on alway, despite the option is not checked. 
May it causes the crash. This is being fixed in 8.1.1

**Comment by klyte45** [comment]
Definitely fixed in 10.0.1
