### ISSUE TITLE
Route sorting

### ISSUE THREAD

**Issue by EpiccraftTV** [klyte45/TransportLinesManager#240]
When I try to sort the transit routes I have, it will sort them in the incorrect order, no matter what I do.

Examples:
1, 10, 11 ..... 19, 2, 20, 21 and so on.

If I have letters in the suffix then it'll show up like this,
2, 20, 21 ..... 29, 2A, 2B, 3 and so on.

When it should look like this,
1, 1A, 1B .... 9, 9A, 9B, 10, 10A and so on.

It would be really nice to have it sort properly as it would make things a lot easier to find when you have a ton of routes. This happens with both the Color/Code and Line Name sorting options. All my lines use the same color, though it changes color depending on the vehicle type.

**Comment by CanadianMarc** [comment]
Agreed. Would be much more optimal for routes to be sorted like 1, 2, 3, 4, 10, 11, 12, 13, 60, 75, 90, etc. I brought this up a few months ago however Klyte said it was intentionally designed this way, I believe.

**Comment by klyte45** [comment]
The sorting is: Prefix first then suffix.
So it's working as intended and both ways would have pro and cons. So it will remain as is.
