### ISSUE TITLE
Unable to designate station for regional trains only

### ISSUE THREAD

**Issue by ILikeFreightTrains** [klyte45/TransportLinesManager#243]
I cannot unselect the 'Allow Intercity Trains' icon. I can however turn the TLM regional platform settings on and off (but intercity trains still arrive even if no platforms are selected) Any suggestions?

**Comment by EpiccraftTV** [comment]
That's a CS bug, I believe. I'd recommend using this mod to fix it
https://steamcommunity.com/sharedfiles/filedetails/?id=2784268275

**Comment by klyte45** [comment]
After turning on TLM regional lines control, only the remaining regional lines will be concluded, and there's no new regional lines starting that station
