### ISSUE TITLE
[BUG]About bus model select

### ISSUE THREAD

**Issue by Highskyring** [klyte45/TransportLinesManager#246]
**Describe the bug**
Vehicles that are not allowed appear on bus routes.
This is one of the default vehicles in the game, 
My English is not good enough to give a detailed description.,.

**Screenshots**
![IMG_20220425_195419](https://user-images.githubusercontent.com/89213021/165084823-7b3a1988-fec3-432a-b03a-d60f21f42e17.png)

**Comment by klyte45** [comment]
Need to use remove unwanted button to remove buses already in line when changed settings.
Reopen if they spawn even if not selected.

Note: If all is unselected, then all are allowed.
