### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by staituk** [klyte45/TransportLinesManager#249]
hi i am using the Transports lines manager mod.   when i click on a stop, it can beany mode of transport i then click on line overview  i get and error,  the lines show as incomplete and the line name is strange.

but when i  go via the infopanel.  it opens the mod and all is ok
![Screenshot 2022-05-08 222105](https://user-images.githubusercontent.com/105175983/167316533-6d675cb8-585e-41e1-a55f-b47985d8e8f9.png)
![Screenshot 2022-05-08 214229](https://user-images.githubusercontent.com/105175983/167316538-583b289e-c349-4e8a-a820-02d782885df9.png)

**Comment by EpiccraftTV** [comment]
The window that shows up when clicking the "Lines Overview" button on any transit building is the vanilla one, all the transit lines show up in the mod's own window. I'm not sure if that is a bug since it's been like that for at least a few updates now.

**Comment by staituk** [comment]
must be a bug with the mod, as this does not happen if i use "improved public transport " mod,  but i prefer the Transport lines manager mod

**Comment by kfbglobal** [comment]
Great mod - this issue with display doesn't yet seemed resolved? Applies as described in original post and to all lines and all tansport types for me.
![Screenshot 2022-08-22 161859](https://user-images.githubusercontent.com/111768340/185958292-f144e5bc-333d-4771-bfa5-64db231c9c33.gif)
