### ISSUE TITLE
"Near Lines" info view has disappeared from next to building info

### ISSUE THREAD

**Issue by SimplyFenske** [klyte45/TransportLinesManager#257]
"Near Lines" info view has disappeared from next to building info. Is there a Keyboard shortcut to bring it back?

Also is there a way to change line names from one district location to another or even say the line is local? Right now it tells me Sunken Station to Hawthorne Park. I would rather it not have the transportation building asset name in the line name if possible.

**Comment by klyte45** [comment]
Check again to see the near lines after enabling it in pause menu mod options
There you can also set which kind of asset/district can be used to name a line
