### ISSUE TITLE
[BUG] Near Lines & Outside Connections way off to the right

### ISSUE THREAD

**Issue by nleanba** [klyte45/TransportLinesManager#260]
**Describe the bug**
When clicking on a station building, the "Near Lines" and "TLM Regional Platform Settings" are floating way further to the side than they should, leading them to be off-screen unless the station popup is on the left half of the screen.

**Game Logs**
https://ufile.io/nv28z1b7

**Screenshots**
![image](https://user-images.githubusercontent.com/25827850/172417672-2da70d8f-f997-47bf-9444-f4f1b63bb84f.png)

**Additional context**
See below for list of installed mods (Compatibility report), might be a weird interaction:

81 Tiles (Fixed for 1.2+), https://steamcommunity.com/sharedfiles/filedetails/?id=576327847
Advanced Stop Selection (ex MTSE), https://steamcommunity.com/sharedfiles/filedetails/?id=1394468624
Better Road Toolbar, https://steamcommunity.com/sharedfiles/filedetails/?id=2502526929
Compatibility Report, https://steamcommunity.com/sharedfiles/filedetails/?id=2633433869
CSL Map View, https://steamcommunity.com/sharedfiles/filedetails/?id=845665815
Custom Animation Loader (CAL) [disabled], https://steamcommunity.com/sharedfiles/filedetails/?id=1664509314
Elevated Stops Enabler [disabled], https://steamcommunity.com/sharedfiles/filedetails/?id=634913093
Environment Changer (+ Improved Theme Selection ), https://steamcommunity.com/sharedfiles/filedetails/?id=611254368
Extended Managers Library 1.0.3, https://steamcommunity.com/sharedfiles/filedetails/?id=2696146165
Extra Landscaping Tools, https://steamcommunity.com/sharedfiles/filedetails/?id=502750307
Extra Train Station Tracks ( ETST ), https://steamcommunity.com/sharedfiles/filedetails/?id=515489008
Find It! 2, https://steamcommunity.com/sharedfiles/filedetails/?id=2133885971
Fine Road Anarchy 2.0.2, https://steamcommunity.com/sharedfiles/filedetails/?id=1844440354
Fine Road Tool 2.0.4, https://steamcommunity.com/sharedfiles/filedetails/?id=1844442251
Harmony 2.2-0 (Mod Dependency), https://steamcommunity.com/sharedfiles/filedetails/?id=2040656402
Hide TM:PE Unconnected Tracks, https://steamcommunity.com/sharedfiles/filedetails/?id=2019097300
Hide TMPE crosswalks V3.0  [stable], https://steamcommunity.com/sharedfiles/filedetails/?id=1934023593
Improved Lane Connections v2, https://steamcommunity.com/sharedfiles/filedetails/?id=2119310640
Intersection Marking Tool 1.8.2, https://steamcommunity.com/sharedfiles/filedetails/?id=2140418403
Loading Screen Mod temporary fix for Airports DLC, https://steamcommunity.com/sharedfiles/filedetails/?id=2731207699
Metro Overhaul Mod (MOM), https://steamcommunity.com/sharedfiles/filedetails/?id=816260433
Movable Bridge Mod (Beta) [disabled], https://steamcommunity.com/sharedfiles/filedetails/?id=2496034669
Move It, https://steamcommunity.com/sharedfiles/filedetails/?id=1619685021
Network Multitool 1.2, https://steamcommunity.com/sharedfiles/filedetails/?id=2560782729
Network Skins (Airports DLC compatible), https://steamcommunity.com/sharedfiles/filedetails/?id=1758376843
Network Tiling, https://steamcommunity.com/sharedfiles/filedetails/?id=1274199764
Node Controller Renewal 3.1.3, https://steamcommunity.com/sharedfiles/filedetails/?id=2472062376
One-Way Train Tracks, https://steamcommunity.com/sharedfiles/filedetails/?id=724382534
Picker, https://steamcommunity.com/sharedfiles/filedetails/?id=2172488844
Ploppable RICO Revisited 2.4.12, https://steamcommunity.com/sharedfiles/filedetails/?id=2016920607
Precision Engineering, https://steamcommunity.com/sharedfiles/filedetails/?id=445589127
Procedural Objects [disabled], https://steamcommunity.com/sharedfiles/filedetails/?id=1094334744
Prop Anarchy 0.7.5, https://steamcommunity.com/sharedfiles/filedetails/?id=2696146766
Roundabout Builder, https://steamcommunity.com/sharedfiles/filedetails/?id=1625704117
Snooper, https://steamcommunity.com/sharedfiles/filedetails/?id=1435741602
Stats [disabled], https://steamcommunity.com/sharedfiles/filedetails/?id=1410077595
Stops & Stations, https://steamcommunity.com/sharedfiles/filedetails/?id=1776052533
TM:PE 11.6.4.8 STABLE (Traffic Manager: President Edition), https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252
Toggle It!, https://steamcommunity.com/sharedfiles/filedetails/?id=1764637396
Tram Station Track, https://steamcommunity.com/sharedfiles/filedetails/?id=707497031
Transport Lines Manager 14.3, https://steamcommunity.com/sharedfiles/filedetails/?id=1312767991
Tree Anarchy 1.3.5, https://steamcommunity.com/sharedfiles/filedetails/?id=2527486462
UnifiedUI (UUI) 2.2 [Stable], https://steamcommunity.com/sharedfiles/filedetails/?id=2255219025
Unlimited Money [built-in]
Unlimited Oil And Ore [built-in]
Unlimited Soil [built-in]
Unlock All [built-in]
Upgrade Untouchable: Convert stations, https://steamcommunity.com/sharedfiles/filedetails/?id=2629141193
Yet Another Toolbar, https://steamcommunity.com/sharedfiles/filedetails/?id=2448994345
Zoning Adjuster 1.5.1, https://steamcommunity.com/sharedfiles/filedetails/?id=2389414419

**Comment by klyte45** [comment]
Seems that another mod is changing the width of the vanilla panel, and messing the position calculations
Once TLM will be rebuilt with IPT soon, it won't be fixed
