### ISSUE TITLE
[BUG] Interface isn't working and Line Names are wrong

### ISSUE THREAD

**Issue by DavidThuss** [klyte45/TransportLinesManager#261]
**Describe the bug**
The buttons on the interfaces do not properly work: I can't enter the Main Menu directly; when trying to enter it via the vanilla transport menue and clicking on the magnifying glass: no reaction. I can open a specific line menue, with line names etc. still in tact, but when I when I want to access the Lines Overview and click on the button: no reaction. --- I managed to enter the lines overview menue via the alternative route of clicking on the individual trains and then accessing the lines overview. When I saw the different lines the names were all weird numbers and not the original names I had chosen for them; and there was a "line not complete sign" next to the line name as you can see in the screenshots. Additionally, I noticed that there are fewer tram lines than there used to be and that, as a general result, the transport system seems to have stopped working as I have a wave of "not enough workers" and "not enough goods" in the city.

**To Reproduce**

**Game Logs**
Here: https://ufile.io/rk4lpubr

**Screenshots**
![2022-06-07](https://user-images.githubusercontent.com/107064048/172434843-42e1c21d-13a8-48e6-97a4-f7673e1dca7d.png)
![2022-06-07 (2)](https://user-images.githubusercontent.com/107064048/172435356-5480b1eb-22e2-45ad-bab2-233d505d35b3.png)
![2022-06-07 (3)](https://user-images.githubusercontent.com/107064048/172436351-d4362e06-bc3a-4f80-9c99-9faa4dd924b3.png)

**Additional context**

**Comment by Cereal4Dinner** [comment]
I was able to access the vanilla "Lines Overview" window by the button on the vehicle info panel. "Line Details" window's button works correctly.
![Screenshot 12](https://user-images.githubusercontent.com/64340180/185788743-c16e9bed-4301-4a0d-9cde-c2f5dcfae9a2.png)
