### ISSUE TITLE
The Mod F:\Games\Cities_Skylines\Files\Mods\1312767991 [0Harmony.dll, TransportLinesManager.dll] has caused an error [ModException] [BUG]

### ISSUE THREAD

**Issue by cn4000** [klyte45/TransportLinesManager#263]
This is what I get
- I clicked ok to close the exception window and was able to enter the game. But some stuff don't work

1. The transport menu doesn't open whenever I click on the magnifier icon. But if I manually say click on a bus and click Line Detail and Line Overview, I could open the panel. But if I click Line Overview after I clicked Line Detail, nothing happened.
2. The texts on the Line Overview page is just cryptic now, bunch of random letters.
![image](https://user-images.githubusercontent.com/91547455/172510783-8b278f54-ba90-47b2-b71c-14b0e78695e7.png)

Details:
System.TypeLoadException: Could not load type 'UnifiedUI.Helpers.UUIHotKeys' from assembly 'TransportLinesManager'.
at Klyte.Commons.Interfaces.BasicIUserMod`3.OnLevelLoadedInherit (ICities.LoadMode) <0x001c5>
at Klyte.Commons.Interfaces.BasicIUserModSimplified`2.OnLevelLoaded (ICities.LoadMode) <0x00029>
at (wrapper dynamic-method) LoadingWrapper.LoadingWrapper.OnLevelLoaded_Patch1 (LoadingWrapper,SimulationManager/UpdateMode) <0x0008b>

**Comment by 1timothy412** [comment]
[UnifiedUILib.log](https://github.com/klyte45/TransportLinesManager/files/8857507/UnifiedUILib.log)
Here's the log

**Comment by DavidThuss** [comment]
I have the same problem, I tried uninstalling Transport manager, saved the game without it and then reinstalled it and it worked for a short period of time, but now the problem is back.

**Comment by DavidThuss** [comment]
Hey I just found a page that offers a solution https://github.com/klyte45/TransportLinesManager/issues/220
