### ISSUE TITLE
Can't see line overview if I put a stop near a cable car line

### ISSUE THREAD

**Issue by Edoardo396** [klyte45/TransportLinesManager#27]
As you can see from the title and the screenshots I have problems when I try to put a stop (in the screenshots I use buses but it is the same with Trams and trains, don't know with metro) near a cable car stop. The info panel does not open by clicking the magnifier button and it open if I open it indirectly by opening another line and clicking on the coincidence but it is bugged.

Still, the line works fine.

And also I can't see prefixes on any line. Do I have to set something?

Am I missing something or is it just a bug? Thanks for the mod anyway, it is great!

Sorry for my English but I am not from a English-speaking country.

![20180618110057_1](https://user-images.githubusercontent.com/13950625/41534592-611cd370-72ff-11e8-837b-0ad688942c25.jpg)
![20180618110050_1](https://user-images.githubusercontent.com/13950625/41534598-633ee2ce-72ff-11e8-974f-168ac3ee938a.jpg)
![20180618110038_1](https://user-images.githubusercontent.com/13950625/41534602-664353e2-72ff-11e8-85a8-f8f8151be633.jpg)

**Comment by klyte45** [comment]
Did you selected the option to show the cable car stations in the linear map? This is on pause menu options.

**Comment by Edoardo396** [comment]
Yes, I enabled it, the problem has been solved with the latest updates,.
