### ISSUE TITLE
[BUG] Some passengers still wait for buses that have already ended service

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#270]
**Describe the bug**
Some passengers still wait for buses that have already ended service. More info on additional context.

**To Reproduce**
(difficult to describe a deterministic procedure to reproduce this)

**Game Logs**
(no)

**Screenshots**
(no)

**Additional context**
Currently this mod can clear the passengers waiting at each stop right when the bus line stops service, and prevents new passengers from using those bus stops, but it did not prevent "travel-in-progress" passengers traveling to the bus stops. For example, maybe the passenger in question hasn't yet arrived at the bus stop when the bus line stops service.

A way of fixing this is to add in regular check to release those passengers from waiting for something impossible. We already have hourly checks for disabling bus stops and clearing passengers, might as well repeat everything every hour when the line is not in service.

**Comment by klyte45** [comment]
Well, I did a check now, and the passengers are behaving as intended: They go to stop of the deactivated line and, noticing it's closed, they go back to find another route.

Any new test case please reopen.
