### ISSUE TITLE
[BUG] Tweaks of the Traffic lines are not saved by the mod?

### ISSUE THREAD

**Issue by Parala2333** [klyte45/TransportLinesManager#279]
**Describe the bug**
After opening an old save, I discovered that all the tweaks I made to the traffic lines (Metro budgets,etc.) are not saved by the mod. Is this a compatbility issue with the new dlc or another mod?

**To Reproduce**
1. Open an previous-version saved game.
2. Make some tweaks to any of the traffic line in the mod menu.(to change budgets, set the maxmium passenger number,etc.)
3. Save the game and exit CSL.
4. Reopen the CSL and load the game again.
5. Discover that all of the above changes are reset to default.

**Game Logs**
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/9583636/output_log.txt)

**Additional context**
It happened after the recent DLC update. My version now is 1.15.0-f7.

**Comment by vnnc** [comment]
Same issue here.

**Comment by smallconan** [comment]
Me too.All changes will be restored to their default values on the next load

**Comment by klyte45** [comment]
Check the current release, it must be solved
Version: v14.3.0 r2

**Comment by Parala2333** [comment]
> Check the current release, it must be solved Version: v14.3.0 r2

Thanks for quick fix!! Now updated and this closed thank you!
