### ISSUE TITLE
[BUG] Error when game loads.

### ISSUE THREAD

**Issue by sergjack2015** [klyte45/TransportLinesManager#280]
All of these pop-ups appear when I load my savegame.

![image](https://user-images.githubusercontent.com/80580018/190705293-2bde20dc-6ef4-4490-96b7-dd58f7fd11cb.png)
![image](https://user-images.githubusercontent.com/80580018/190705402-55a945e8-a053-4c8a-9341-668e1b81c6b7.png)
![image](https://user-images.githubusercontent.com/80580018/190705430-3940970c-3054-4b43-82d3-f1675f43c319.png)
![image](https://user-images.githubusercontent.com/80580018/190705464-d6caae06-3822-4de9-bb0b-e928955f5145.png)
![image](https://user-images.githubusercontent.com/80580018/190705490-d937df22-72ed-4564-8cdd-71f5a52ec0f0.png)
![image](https://user-images.githubusercontent.com/80580018/190705543-4fafbe23-389b-46db-b1d3-4ec5ed401f05.png)

Here's the output log:

[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/9586368/output_log.txt)

**Comment by klyte45** [comment]
It seems to be a side effect from today's patch. I will try to look into it.
But, it won't prevent you from play the game as normal, but the settings files won't be loaded (but the new setup will be saved)
Again, I will try to solve it to not prejudice in your case.

**Comment by sergjack2015** [comment]
Okay, but does that mean that my transport lines' settings will be reset? a.k.a. will my vehicle selection, termini, ticket cost etc. be reset?

**Comment by klyte45** [comment]
while it's not fixed, yep
but don't worry I'm looking on it

**Comment by klyte45** [comment]
It's on Workshop under version v14.3.0r3. Please try again.

**Comment by sergjack2015** [comment]
It loads successfully now.
