### ISSUE TITLE
Can't sort lines by any parameter

### ISSUE THREAD

**Issue by Xyrhenix** [klyte45/TransportLinesManager#31]
I cannot sort lines by any of the paramters which I would ordinarily be able to sort them by. Normally, to sort lines, you would click one of the labels in the red box of the below image, but clicking them has no impact on the list.

![image](https://user-images.githubusercontent.com/39814064/43049594-23016d2c-8df2-11e8-8cd6-1fb229f64e0f.png)

**Comment by klyte45** [comment]
Fixed in 10.0.1
