### ISSUE TITLE
Crash when creating a new bus line

### ISSUE THREAD

**Issue by dourouc05** [klyte45/TransportLinesManager#32]
Very nice mod! 

Yesterday, the game started to have troubles when creating a new bus line (I already have 25 or so of them). Most of the times, the simulation just stops: cars stop moving, I cannot add more roads, or even save the game (in this case, in the upper right corner, the Save text appears, but the indicator does not turn around). I managed to make it crash properly, and I could figure out that this mod was causing the problem (more specifically, the part creating the name of the station). I tried creating new lines in both empty areas (just roads, no building in the surrounding) and in already filled areas (completely zoned, with service buildings all around), with the same issue. I could also create bus lines previously, also with this mod, so I guess it is more of a recent update causing the troubles. 

I tried to disable the mod and Klyte Commons, and everything went back to normal (i.e. I was able to create new bus lines).  

Here are the results of the crash: 
* output_log.txt: https://gist.github.com/dourouc05/76512d731d9560408ca1338391fa1848
* error.log: https://gist.github.com/dourouc05/ff6ebc220dc08e5783238bd5822ff752
* crash.dmp: https://gist.github.com/dourouc05/ca70a174a30a34713218de44d89bada7

**Comment by klyte45** [comment]
Please check if it still happening in version 13.5

**Comment by dourouc05** [comment]
Actually, it stopped happening quite a while ago (at least a few months), and I no more have access to the cities I was using in 2018. I suppose we can close this issue.
