### ISSUE TITLE
Train Stops at Modular Stations Disconnected on Load, Reconnecting Lines Causes CTD

### ISSUE THREAD

**Issue by dragonshardz** [klyte45/TransportLinesManager#33]
On map load, train stops at modular stations complain that they are not connected to the rest of the line. Reconnecting the line causes a CTD 4/4 times I tried this issue, and the error logs support it being some sort of issue with TLM. Logs and dump are [attached.](https://github.com/klyte45/TransportLinesManager/files/2292306/2018-08-14_214144.zip)

**Comment by klyte45** [comment]
Please check if it still happening in 13.5, once it usually happened in v10

**Comment by klyte45** [comment]
Closing due inactivity
