### ISSUE TITLE
For a while now, in most of my C:S sessions I cannot go to line view from the lines list

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#36]
For a while know (since previous mayor update), I've had an issue where the magnifier symbol is missing in most of my games, for example see this video below (watch around 25:20):
https://youtu.be/7Tr0k7KGvTA?t=1527
Only way I can access the line view is by actually finding a bus on the line from the map and enter through that. Very rarely that symbol appears to me.

**Comment by kerts93** [comment]
This looks like was incompatibilty with Service Lines Manager mod

**Comment by klyte45** [comment]
This mod will be remade
