### ISSUE TITLE
Auto line naming is just ???????

### ISSUE THREAD

**Issue by Machine-Maker** [klyte45/TransportLinesManager#39]
Using latest versions of mods, and the auto line naming just spits out ??????? It has the correct [prefix/linenumber] but then its followed by ????????

**Comment by klyte45** [comment]
It means that there's no near reference to name the station, like a road in a place with no district setted and no buildings around. Check your line naming settings to adjust it if not the case (maybe you not selected Train stations to name stops and the stop near the train stations get "?????" , as example)
