### ISSUE TITLE
Changing line color in line list does not save

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#40]
Yesterday I found a bug that changing line color in line list view does not change.

Additionally it would nice to get the color code text field (for example if I want to copy-paste line color from one line to another) from there into the line details view also.

Version 13.5

**Comment by klyte45** [comment]
Well, the color code appears in bottom of the color picker window, when you click in the color field - at least it should.
Marking for review in next patch

**Comment by robsonfz** [comment]
klyte45, as cores realmente não são salvas, seja quando você escolhe ou digita, tanto na tela de linhas quanto na janela de cada linha.
  Além disso, as cores por prefixo também não funcionam. Vou ser sincero que apenas tentei em linhas de ônibus.
