### ISSUE TITLE
Unable to create bus tours or walking tours

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#42]
I'm unable to create any walking tours and bus tours. When I place the stops down, they don't connect to each other. Additionally on placing I'm missing the stop preview.

I suspect it's caused by TLM because the prefix selector/next line selector UI is empty for those line types.

Version 13.5

**Comment by klyte45** [comment]
Just tested in 13.5 and it's working fine. Probably it's a mod conflict. I would need your mod list to check any potential conflicting mod that can break it. The test I just done:
![image](https://user-images.githubusercontent.com/11671356/110968886-d16d3580-8336-11eb-871a-559ee8fbd2e8.png)

**Comment by GameBurrow** [comment]
Just tried again and I noticed, it actually does create the lines, but it doesn't render the line. Checked that by default the eye icon was disabled by default for the tour lines but even when I enabled it, the line still wasn't visible. Here's a video:

https://www.youtube.com/watch?v=MUQg4Gaupzw

Mod list is same as in my other issue: https://steamcommunity.com/sharedfiles/filedetails/?id=941814282
Outpud log I attached into this issue by your request: https://github.com/klyte45/TransportLinesManager/issues/45 is from the same game session where I made this video.

**Comment by GameBurrow** [comment]
Small update on the issue (still have it sadly):

When I just open the Tours view, I see the lines, but as soon as I open the stop add/move/remove tool, it hides the lines and instead starts displaying bus,tram,trolley lines etc.

See gif: https://cloud.sepaurg.eu/s/Fd2SsiQLxg3rGXw/download

**Comment by klyte45** [comment]
Couldn't open the gif... (435MB o.O)

I will double check it

**Comment by klyte45** [comment]
Well, found nothing in v14 either
