### ISSUE TITLE
Lines show as incomplete

### ISSUE THREAD

**Issue by Glock01** [klyte45/TransportLinesManager#43]
All the lines in the transport manager are showing as incomplete, even though all the bus lines are "Working" and my metro lines aren't spawning any subway trains for whatever reason. SIDE NOTE: I am using Metro overhaul Mod, not sure if this conflicts, as far as I'm aware nothing of this conflicts 

http://prntscr.com/vzg4b9

**Comment by klyte45** [comment]
Actually it means that something was preventing the mod to be fully loaded, then you got in a invalid state for line listing screen.
I would need your output_log.txt content to check it. Please open another issue with the full information to I be able to check it.
