### ISSUE TITLE
Add releases downloaded files on Github

### ISSUE THREAD

**Issue by DarthPointer** [klyte45/TransportLinesManager#44]
I have found the mod via SteamWorkshop and want to get it for my EGS game copy. Could you attach the files to download to releases please?

**Comment by klyte45** [comment]
You can get the mod versions at [https://github.com/klyte45/TransportLinesManager/tags](tags page). The required dll to use in game are into **_requiredDll** folder.

The latest version is always the first in this list, with a higher version number
