### ISSUE TITLE
Line statistics views broken

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#45]
See attached images below. So far it seems to be case for all line types. As you can see, column alignments are messed up.

![Cities_hlFyvents5](https://user-images.githubusercontent.com/4341091/102950263-f2aa4c80-44d2-11eb-8d7a-7b6e0a0e12d4.png)
![Cities_Ts3Jr7gBmN](https://user-images.githubusercontent.com/4341091/102950266-f342e300-44d2-11eb-8fae-916353cbe6f9.png)
![Cities_bdbGvRcmLq](https://user-images.githubusercontent.com/4341091/102950269-f4741000-44d2-11eb-97a5-898abc3b7958.png)
![Cities_08TmEmtCeb](https://user-images.githubusercontent.com/4341091/102950272-f5a53d00-44d2-11eb-9389-30e95b6d2eae.png)
![Cities_rHCQBuwrzP](https://user-images.githubusercontent.com/4341091/102950277-f6d66a00-44d2-11eb-8ea8-208bdc8b1bb4.png)

Just incase, here is the list of mods (not assets) I have installed: https://steamcommunity.com/sharedfiles/filedetails/?id=941814282

**Comment by hakil** [comment]
I'm the same, the row views are in disarray.
I like this mod very much, if you can fix it as soon as possible, thank you very much

**Comment by klyte45** [comment]
It's Resize It! fault. It messes all my mods UI.
Remove it and all should be fine

**Comment by GameBurrow** [comment]
Removed resize it, still exists:
![image](https://user-images.githubusercontent.com/4341091/110971349-70a82200-8363-11eb-9926-8bbfb2e0364f.png)

**Comment by klyte45** [comment]
The mods lists still that one?

**Comment by GameBurrow** [comment]
> The mods lists still that one?

Yep.

**Comment by klyte45** [comment]
Can you send me your log after loading a city and getting that problem? The mod have the instruction under this button, if you don't know how to do it.
![image](https://user-images.githubusercontent.com/11671356/110972684-07141d80-833b-11eb-93d9-91774552826a.png)

**Comment by GameBurrow** [comment]
Sure, here you go:
https://gist.github.com/GameBurrow/0eeb5d75dda30dd040ff61bf6575a83f

**Comment by klyte45** [comment]
Hmmm, I'm sure its a mod conflict...
Are you using some mod that change the game rendering? (rendering fix or even MOM)

They would be my next try, removing them and checking if it worked

**Comment by GameBurrow** [comment]
Sorry for taking long to respond.

So I went as far as disabled all mods except yours, even down to the layer of downloading latest version from here and putting _requiredDLLs files it into `%LOCALAPPDATA%\Colossal Order\Cities_Skylines\Addons\Mods` folder and enabling -noWorkshop flag. Issue still persisted without any other mods and assets present.

Alright, I started digging deeper and spend about 2 hours on it. Disabled my external GPU and monitors, noticed the issue dissapeared. Started comparing my monitors and GPUs, ran them in different combinations and found out that the issue is dependant on what resolution the game launches with.

This bug does not appear if the game is launched with 1920 x 1080. **If game is launched with 2560 x 1440 or 3440 x 1440 resolution, the bug appears.** If you change the resolution ingame and do no restart the game, it doesn't change, it changes after game restart.

**Comment by klyte45** [comment]
I see... Well, seems to be a issue that comes from the UI itself, not exactly from the mod. I will see what I can do, but I don't have a 1440p monitor to test possible solutions. So I can't promise I can fix that...

Anyway, I will left this issue open for the future. Any news I will post here. Thanks for the tests you done finding out the problem!

**Comment by GameBurrow** [comment]
If you need any testing to be done, feel free to let me know. I last touched VS Community about 10 years ago (same with C#) but I'm not new to git, nor development itself.

**Comment by klyte45** [comment]
Well, the latest alpha changed some code relative to the UI behavior. Maybe it got solved. I suggest to take a look on it later.

**Comment by GameBurrow** [comment]
Sadly no change:
![image](https://user-images.githubusercontent.com/4341091/115189937-f7cd8000-a0ef-11eb-8302-88b57b9e0d94.png)

**Comment by GameBurrow** [comment]
It seems this version is now breaking texts with rest of the UI (could also be WTS alpha update, added that at the same time, don't have time atm to test only one of them)
![Cities_HVugpvXbVK](https://user-images.githubusercontent.com/4341091/115191192-c3f35a00-a0f1-11eb-9650-ba876f1fbad4.png)
![Cities_QPNsIQTqyj](https://user-images.githubusercontent.com/4341091/115191199-c786e100-a0f1-11eb-9a0e-30d7fba87e6a.png)
![Cities_xCVmgmT4kZ](https://user-images.githubusercontent.com/4341091/115191210-ca81d180-a0f1-11eb-8b36-9aa6b4aec791.png)

Just in case tried restarting and some of them went to normal but new things appeared, like for example district names text changed to like this.

**Comment by GameBurrow** [comment]
Tried again with latest alpha (2547b934a27a4e63f039f5b96cd8920443847368) , original issue still exist and the new one also that breaks text in multiple places in UI.

**Comment by klyte45** [comment]
But this issue was solved?

**Comment by GameBurrow** [comment]
No

**Comment by GameBurrow** [comment]
Fixed on alpha ;)
![image](https://user-images.githubusercontent.com/4341091/117697998-d67e2200-b1cb-11eb-92a4-35ec80f09dc2.png)

**Comment by GameBurrow** [comment]
Hoewer line list has similar bug:
![image](https://user-images.githubusercontent.com/4341091/117698167-1513dc80-b1cc-11eb-8f7a-e5e5a7061340.png)

**Comment by wjhunt78** [comment]
Suddenly all of my line statistics are invisible! Even after restarting/reloading, it remains the same. The place where the numbers should be is totally empty. Screenshot and output log attached.
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/6493173/output_log.txt)
<img width="960" alt="tlm mod screenshot 2" src="https://user-images.githubusercontent.com/83703504/118474132-061cb500-b70b-11eb-86b0-b406e613cd92.png">

**Comment by klyte45** [comment]
It is being caused by latest update of the FPS Booster + Patch Loader. Disabling both solve the problem: 
![image](https://user-images.githubusercontent.com/11671356/118687915-ec976e00-b7db-11eb-9654-52d11164741a.png)
The Write the Signs panel was also failing rendering because of it, as well the game was crashing right after the city getting loaded.

The author was notified about the issue and will check it later. For now, consider disabling both mods

**Comment by wjhunt78** [comment]
Disabling both mods did indeed solve the problem for now, as wel as a lot of other text rendering issues. Thanks!

**Comment by klyte45** [comment]
FPS booster will be updated soon to solve this problem, the fix is already implemented
