### ISSUE TITLE
Opening TLM crashes game

### ISSUE THREAD

**Issue by linuxgamer19** [klyte45/TransportLinesManager#47]
Opening the TLM tab crashes the game. The issue probably has something to do with mono. A similar issue comes up with some other mods when using the mono version that comes with the game instead of installing the newest version separately.

Operating system: Linux

End of the `player.log` file:

```
Receiving unhandled NULL exception
#0  0x007ffdfee4c800 in funlockfile
#1  0x007ffdfee4cea8 in setlinebuf
#2  0x007ffdfee4cff8 in g_free
#3  0x007ffdfee4d0d8 in mono_once
#4  0x007ffdfee4d398 in mono_once
#5  0x007ffdfee4d3b8 in mono_once
#6  0x007ffdfee4d3c8 in __libc_secure_getenv
#7  0x007ffdfee4d418 in exit
#8  0x007ffdfee4d428 in mono_thread_exit
#9  0x007ffdfee4d438 in mono_method_marked_as_wrapperless
#10 0x007ffdfee4d6f8 in mono_amd64_throw_exception
#11 0x007ffdfee4d8b8 in (Unknown)
#12 0x007ffdfee4d8c8 in (Unknown)
#13 0x007ffdfee4d8d8 in (Unknown)
#14 0x007ffdfee4d8e8 in mono_set_defaults
#15 0x007ffdfee4dcc0 in mono_runtime_invoke
#16 0x007ffdfee4dcf0 in std::vector<core::basic_string<char, core::StringStorageDefault<char> >, std::allocator<core::basic_string<char, core::StringStorageDefault<char> > > >::~vector()
#17 0x007ffdfee4dd20 in std::vector<core::basic_string<char, core::StringStorageDefault<char> >, std::allocator<core::basic_string<char, core::StringStorageDefault<char> > > >::~vector()
#18 0x007ffdfee4dd40 in ps_hints_apply
#19 0x007ffdfee4e2c0 in std::vector<core::basic_string<char, core::StringStorageDefault<char> >, std::allocator<core::basic_string<char, core::StringStorageDefault<char> > > >::~vector()
#20 0x007ffdfee4e390 in ps_hints_apply
#21 0x007ffdfee4e600 in ps_hints_apply
#22 0x007ffdfee4e6b0 in std::vector<core::basic_string<char, core::StringStorageDefault<char> >, std::allocator<core::basic_string<char, core::StringStorageDefault<char> > > >::~vector()
#23 0x007ffdfee4e6d0 in zcfree
#24 0x007ffdfee4f4d0 in __libc_start_main
#25 0x007ffdfee4f5a0 in zcfree
```

**Comment by klyte45** [comment]
Well, I'm afraid that I can't help you so much, because I'm only have Windows system.
But I have a suspect about what can be the source of the problem, in my compile time I might be using C# version 8. It may be affecting this compatibility. 

I will make a version using an older version of C# in a separated branch and then ask you to test it, OK?

**Comment by linuxgamer19** [comment]
Sounds good! I'll try that then.

**Comment by klyte45** [comment]
Nice, I will do it until next weekend and send a reply here when it get ready

**Comment by klyte45** [comment]
Well, here it go: https://github.com/klyte45/TransportLinesManager/tree/dev/c%237.x/_requiredDLLs

I hope it works

**Comment by linuxgamer19** [comment]
The update made TLM more stable but now some other type of mono-related crash happens in other places. I'll continue looking at it myself. Thanks for your help!

**Comment by linuxgamer19** [comment]
Hi.
The link for the fork with the older C# version doesn't seem to work anymore. I'd like to download it again since I think I lost the previous download in a reinstall or something.

**Comment by klyte45** [comment]
It's safe now to get from the master branch: https://github.com/klyte45/TransportLinesManager/tree/master/_requiredDLLs
The code was merged with the main mod version, so it shall not cause any probelm
