### ISSUE TITLE
Settings not saving when loading saved game

### ISSUE THREAD

**Issue by Yorkie-Pudd** [klyte45/TransportLinesManager#50]
Whenever I set how many vehicles run at certain times and what vehicles are running on the line it works great while I'm still in game, but once I've saved my game and quit then load my game again all these settings have gone and I have to redo them all over again.

**Comment by klyte45** [comment]
Yep, I got this bug. It's affecting other mods like Write the Signs. I'll release a fix this week. 

Thanks for reporting!

**Comment by Yorkie-Pudd** [comment]
Amazing, thank you

**Comment by klyte45** [comment]
Already released on workshop! Please check it again

**Comment by Yorkie-Pudd** [comment]
Just tested it now and it works great. Thank you
