### ISSUE TITLE
Issue with prefix vehicle selector - it seems to spawn only the model I selected first (except buses)

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#51]
I've noticed on my new playthrough that if I have selected multiple vehicles per prefix, it seems to spawn only vehicles I selected first for the prefix (except buses). 

I have my budgets set so that it reduces the amount of vehicles at night so over time I should see more models appear even if I use the replace model tool (that tool ofc replaces all vehicles with one model even if I have multiple set per prefix). With buses I do see more models on the streets over time but it doesn't seem to be case with for example trolleybuses and metros, they always spawn the same model. 

This bug is something newer as it didn't appear in my previous save (which I finished about month or two ago).

Here's an example, I have created prefix C - City - 18 for trollebuses. It has 3 models enabled: D3S Solaris Trollino 18 (IV), Solaris Trollino 18 mk3 and Solaris Trollino mk2. I selected mk3 first and immediately after mk2 and IV. Only mk3's are on the line.
![mWnvKIWhDY](https://user-images.githubusercontent.com/4341091/113051686-ee1ac180-91ae-11eb-9464-6b083395e3f8.gif)

**Comment by klyte45** [comment]
You said they haven't changed immediately or they are not being spawned from the depots?

**Comment by GameBurrow** [comment]
> You said they haven't changed immediately or they are not being spawned from the depots?

WIth trolley's and metro's, both.
With buses, only immediate replacement behaves like this, but from depot it seems there are multiple models coming out. 
Haven't tried other transport types yet.

**Comment by GameBurrow** [comment]
Here's a an example gif for the same for the same line/prefix I showed in first post (where I had 3 different Solaris 18 models enabled):
https://streamable.com/xc8wtf

As you can see, it only sends out mk3 versions of the buses, when I increased the budget-

**Comment by GameBurrow** [comment]
One more update, it seems my previous statement that buses are exception is not true. It mostly still dumps out one model per prefix (with one of the tests I did, out of about 10 buses, only 1 was different model which is even more strange)

**Comment by GameBurrow** [comment]
Just incase tried without any other mods also, same deal:

![image](https://user-images.githubusercontent.com/4341091/113485765-fb3df600-94b7-11eb-9d28-277d8ca9b5f9.png)

Just incase removed all buses from line, ticked used specific config in this line and tried again. Again only the bus models I selected first appeared

**Comment by klyte45** [comment]
hmmm... I guess I know what's happening. Try deselecting the default bus model. See if the others models will be spawned.

The TLM algorithm will not change the game choose if it's already allowed in the current model selection. And by default the vanilla bus is the default model for bus lines... I will double check it when I get back to TLM.

**Comment by GameBurrow** [comment]
With mods & assets enabled I always have vanilla buses deselected, still only 1 model per line apppears.
