### ISSUE TITLE
Issue with line colors

### ISSUE THREAD

**Issue by brandontravis** [klyte45/TransportLinesManager#53]
Possibly related to #40 but I'm not entirely sure of what that issue is.

Regardless, when I am looking at all of my lines (say, for Metro), if I copy a Hex code from another line and paste it into a lines HEX field, the preview color in the Klyte panel updates to the correct color, however the line color doesn't actually change. The only way I can get the line color to change is by using my mouse to select a color in the color palette

**Comment by klyte45** [comment]
Is the same in POV of feature, but it's different code.  A fix for that must be ready as soon as Addresses V3 gets released - this bug will be fixed there then applied here after.

Watch the milestone  [at Addresses mod project](https://github.com/klyte45/AddressesMod/milestone/1)
