### ISSUE TITLE
Questions on ticket price control

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#58]
Hi there, thanks for this wonderful mod!

Currently this mod allows setting the ticket price in the range of $1 to $5, but the default price of different transport types may not necessarily equal to $1 (e.g. from the info of this https://steamcommunity.com/app/255710/discussions/0/2666626316171617090/ the default ticket price of metro is $2)

Right now the UI displays $1 as "default" and for me, this creates confusion because at some point my metro lines were running at "default" ($1) but were losing money, and my 1st impression was that "default" meant $2 and so something seemed strange and inconsistent. It was only after I unlocked the ticket price controller do I finally realize "default" meant $1.

Might there be a way for us to adjust fare such that it is based on a multiplier on the actual default fare of the transport type? EG I can adjust the metro price to be 200% of the real default value ($2) instead of having to explicitly set the price to $4.

**Comment by klyte45** [comment]
Actually the default values come from this screen:
![image](https://user-images.githubusercontent.com/11671356/115084469-5839a300-9edf-11eb-9c0b-d8cdddcdfa2b.png)
Note that using `0` as value means that it will get the game default price ($1 for buses, $2 for mono/train/metro, $1.15 for blimps, etc). And it seems to be working well.
![image](https://user-images.githubusercontent.com/11671356/115084785-b8c8e000-9edf-11eb-9d2e-d1ffd4ba2fd5.png)

About the range limited from 1 to 5, there's no default transport type that uses a higher value than $5, I guess there's no need to change this, once using percentage would make it less clear to use.
