### ISSUE TITLE
[Alpha] Breaking game font

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#70]
Split this into separate issue from https://github.com/klyte45/TransportLinesManager/issues/45 as it's different issue

Somewhere from around Apr 18, the alpha version of the mod started breaking the font in the game. It's still broken to this date.

![Cities_HVugpvXbVK](https://user-images.githubusercontent.com/4341091/115191192-c3f35a00-a0f1-11eb-9650-ba876f1fbad4.png)
![Cities_QPNsIQTqyj](https://user-images.githubusercontent.com/4341091/115191199-c786e100-a0f1-11eb-9a0e-30d7fba87e6a.png)
![Cities_xCVmgmT4kZ](https://user-images.githubusercontent.com/4341091/115191210-ca81d180-a0f1-11eb-8b36-9aa6b4aec791.png)
![Cities_C6I3uksFFg](https://user-images.githubusercontent.com/4341091/115986767-7cba0d00-a5ba-11eb-96a9-81e7e3c9ed3c.jpg)
![image](https://user-images.githubusercontent.com/4341091/115986780-8d6a8300-a5ba-11eb-8e1c-9a647dbbfb4c.png)

As you can see, it can be anything that is broken: street, district names, to UI elements like balance, population and even other mod things like Prop & Tree Anarchy mod on/off text and more.

It doesn't break everythin immediately, game runs a for half a minut and then it starts breaking them.
Text that changes dynamically, will fix it self over time, street and district names also can be fixed if I edit the text for a bit.

And once the text fixes itself, it doesn't seem to break again for the same game session.

**Comment by klyte45** [comment]
Actually this is an old known game bug. The fonts processor is weak and is not so uncommon to this to happen. 
It happens because the font texture was regenerated but the characters mesh weren't by some internal exception not handled - sometimes in mod sides and, in worst cases, sometimes in the native game code. 

TLM might made it worst with the line icon inline generator, to show the line name inside a form. I'm planning to bring the WTS transport line icon image cache system to TLM, but don't know if I would do it in v14.

**Comment by klyte45** [comment]
Well, this will be fixed when the related commons version get into the current version of the mod, probably in the next TLM patch release.

**Comment by klyte45** [comment]
Reopened because it's not in TLM yet... A testable build will be available soon

**Comment by klyte45** [comment]
Please take a look in the alpha branch. The fix is there.

**Comment by GameBurrow** [comment]
Took a bit longer to happen but happened with alpha.

**Comment by klyte45** [comment]
Can you send your log, after this happened? Maybe it's not TLM itself, but other of my mods.

**Comment by GameBurrow** [comment]
> Can you send your log, after this happened? Maybe it's not TLM itself, but other of my mods.

Here you go (game is still running): https://gist.github.com/2fe53afb6ba4c3b4ac16db26cf730494

**Comment by GameBurrow** [comment]
Sorry for taking a long time to try, haven't had time. Still same. Takes longer time to break, but it does.

Here's the logfile: https://gist.github.com/GameBurrow/a6a65a235d077ba7f50f41e19f8343bf

**Comment by klyte45** [comment]
The final solution is coming this weekend
Be sure that all mods that you have are updated to version released last week. TLM, WTS and ACE are the least to be updated to make this issue finally disappear
