### ISSUE TITLE
Header labels in lines overview panel are all over the place

### ISSUE THREAD

**Issue by naim** [klyte45/TransportLinesManager#72]
![Screenshot 2021-04-28 223751](https://user-images.githubusercontent.com/92351/116496247-9eddb480-a872-11eb-8c49-decc9f7195a0.png)
![Screenshot 2021-04-28 223809](https://user-images.githubusercontent.com/92351/116496249-9f764b00-a872-11eb-8ce1-54ffacfdda07.png)
![Screenshot 2021-04-28 223838](https://user-images.githubusercontent.com/92351/116496250-9f764b00-a872-11eb-8a85-d94d70ab461a.png)
![Screenshot 2021-04-28 223733](https://user-images.githubusercontent.com/92351/116496251-a00ee180-a872-11eb-816f-5efd53ead02d.png)

Noticed that the headers for each of the different transport types had strange header positioning issues. Seems to be cosmetic only.

Took a quick look at the open and recently closed issues and didn't see this mentioned anywhere. Obviously this is minor and not a big deal, but thought it might be helpful to know.

**Comment by klyte45** [comment]
Are you using a 1440p resolution? There a bunch of problems like this related in other issues by players in that resolution

**Comment by naim** [comment]
Yeah, I'm on 32:9 (5120x1440) using the "More Aspect Ratios" mod; that's got to be it. I'll close this since it isn't a general issue. Thanks for the quick reply!
