### ISSUE TITLE
Error when selecting vehicle models

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#74]
I previously used ModTools to debug my mod and am too lazy to disable it so I noticed this bug when I am not in modding mode and in playing mode

So I noticed that when I try to enable/disable vehicle models in the model selection, ModTools will pop up and say there is an error, like this:

![Screenshot (26)](https://user-images.githubusercontent.com/17726797/116692020-47fcea00-a9ee-11eb-867d-f2a41c4b72f8.png)

```
[ERROR] Klyte.Commons.Utils.LogUtils.DoErrorLog():
TLMv13.5 checkbox event: 2395292899.Volvo B8L WEG3 12m Generic_Data => True at Klyte.TransportLinesManager.Extensors.TLMTransportLineExtension[25]
```

This has happened for a long time but I keep dont have time to report this, now I have some time and report this.

I guess this is some debug logging that you forgot to disable? Anyway this "bug" seems harmless, only annoying.

**Comment by klyte45** [comment]
This log is from version 13.5, so please test if it's still happening in v14 (I believe it's not)

**Comment by Vectorial1024** [comment]
Wait does that mean v14.0 is released? I am not following too closely.

**Comment by klyte45** [comment]
Yep, it was yesterday. I updated the master with the new Workshop version

**Comment by Vectorial1024** [comment]
Well that was an unexpected welcome. Will just re-test later.

**Comment by Vectorial1024** [comment]
And yes this bug was gone after the latest update

Nice work getting the 16:9 issues sorted out!
