### ISSUE TITLE
Auto Line name only goes "<Somewhere>"

### ISSUE THREAD

**Issue by Lamandus** [klyte45/TransportLinesManager#80]
Auto naming doesn't work for me right now. It only shows that: 
![grafik](https://user-images.githubusercontent.com/33199510/116810219-db473400-ab42-11eb-9740-bc4708b627b7.png)

When activating "road adress" for autonaming
![grafik](https://user-images.githubusercontent.com/33199510/116810231-ebf7aa00-ab42-11eb-8517-b48e78c6ea54.png)

whenever I switch it on and even save it as default. Returning back in the option it is deactivated again.

![grafik](https://user-images.githubusercontent.com/33199510/116810261-1fd2cf80-ab43-11eb-8b53-b8e25036e2ae.png)
it knows the street/names but it won't use them.

**Comment by klyte45** [comment]
Well, it seems to be a simple issue. Hopefully it will be solved in the patch that might be released later this month

**Comment by DarkWolf7** [comment]
I'm having this issue too, glad to see it's being worked on!
