### ISSUE TITLE
Wrong Type(s) of Sightseeing Buses Keeps Spawning

### ISSUE THREAD

**Issue by KoalaPrince** [klyte45/TransportLinesManager#81]
I set up a Sightseeing bus service (Parklife Addon DLC), and tried to manage it through TLM, I selected [this type](https://steamcommunity.com/sharedfiles/filedetails/?id=1399835119&searchtext=sightseeing) of sightseeing bus, while did not select the default bus, it turned out that the default sightseeing bus keeps spawning instead of the selected type.

**Comment by klyte45** [comment]
I admit I never tested model selection for sightseeing buses... I will check this

**Comment by klyte45** [comment]
Fix available to test at [alpha branch version](https://github.com/klyte45/TransportLinesManager/tree/alpha/_requiredDLLs)
