### ISSUE TITLE
Make it possible to select terminus stops when not using express services

### ISSUE THREAD

**Issue by wjhunt78** [klyte45/TransportLinesManager#82]
As a Write The Signs user, I'm very happy to be able to select terminus stops, so that I can determine myself which station appears on the front of the bus.

Unfortunately, this feature (right click on stop so it becomes a star and is marked as terminus) is only available when using express services (that I don't particularly like because of the unbunching behaviour).

I would love to be able to use the feature of terminus stops even when express services are turned off. Could you make this possible?

**Comment by klyte45** [comment]
I will avail this possibility in next patch, later in this month

**Comment by wjhunt78** [comment]
Thank you so much!

**Comment by klyte45** [comment]
It's available for testing at current alpha branch.
Terminal will be available to **ANY LINE** if WTS is enabled, including also train, ferry and others transport types that doesn't support express lines.

**Comment by wjhunt78** [comment]
Have already been testing this today and it's great! I also like that it's available for all transport types now. Thanks Klyte for all your hard work!
