### ISSUE TITLE
There is no bus on every line.

### ISSUE THREAD

**Issue by Trove226** [klyte45/TransportLinesManager#83]
**There is no bus on every line.**

There should be a bus on the line at that time, but none of them go out. About 10-15% of all bus lines have this error. If I reset the current line to default, the bus will go out. I did not experience this error on trams, trolleybuses and trains. (There is no subway, monorail, ferry, airship and helicopter in this city.)

**Comment by Trove226** [comment]
![20210504225228_1](https://user-images.githubusercontent.com/48177958/117509047-75fba480-af81-11eb-9c1d-a200035c9efe.jpg)

**Comment by klyte45** [comment]
For how much simulation time it was running?  It used to delay a little to dispatch the first vehicle.

**Comment by klyte45** [comment]
Well, both the two lines zeroed are new ones, it seems. For how long they were running in simulation without spawning any vehicles?

**Comment by Trove226** [comment]
Not only did it happen on two lines, (about 5-6 lines) but the rest are not visible in the picture. After the update, the error appeared 3 saves later (express, etc).
I once saw a bus appear on the unscaled map (I think it started out of the garage), but by the time I could click on it, it was gone.
