### ISSUE TITLE
The change of vehicle capacity aren't saved

### ISSUE THREAD

**Issue by asmape0104** [klyte45/TransportLinesManager#84]
(I'm not English native speaker, so sorry for my poor English)

Since v14, the capacity of vehicle are not saved.

When I change the capacity of one metro (custom assets) from 180 (assets' default) to 720, save game and resume, it returns to 180.

**Comment by klyte45** [comment]
No worries, I'm not a native speaker too :)

Do you have any output log from the game after this happens? See the "Report-a-bug helper" button in the mod options menu.

**Comment by klyte45** [comment]
Don't worry, I could reproduce here.
Wait for news soon!

**Comment by klyte45** [comment]
Fix available in the current [alpha branch](https://github.com/klyte45/TransportLinesManager/tree/alpha/_requiredDLLs)
