### ISSUE TITLE
Hide/show all lines button partially broken

### ISSUE THREAD

**Issue by wjhunt78** [klyte45/TransportLinesManager#89]
The button to hide/show all lines on the map (the little eye where my cursor on the screenshot is) still works technically, but when I click it, all the individual little eyes from each line are not visually updated. This is kind of confusing. In the attached screenshot, I just clicked the eye to hide all lines. You can see the problem there clearly. Using latest alpha version.

EDIT: Now pressing the show/hide all button does not work at all. Showing/hiding individual lines does work though. Strange..

[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/6493191/output_log.txt)

<img width="960" alt="tlm mod screenshot 1" src="https://user-images.githubusercontent.com/83703504/118474857-d1f5c400-b70b-11eb-9030-f0da8f612e06.png">

**Comment by wjhunt78** [comment]
This issue had (temporarily) been solved by deactivating Patch Loader and FPS Booster Mods. When these mods are updated, I will try to activate them again to see if this issue has been solved.

**Comment by klyte45** [comment]
Well, it must be solved by latest patch of them. Please check and close this if get success
