### ISSUE TITLE
Search Vehicle Feature

### ISSUE THREAD

**Issue by YuLun-bili** [klyte45/TransportLinesManager#90]
I have nearly 100 different buses (approx.) subscribed from workshop and each time I deciding buses using by a line I have to scroll down to search the bus I wanted. really hope you would add a search bar at model selection section

**Comment by klyte45** [comment]
Will be added at 14.1:
![image](https://user-images.githubusercontent.com/11671356/137055374-ed701dca-3c97-47ea-9e60-160115e8cfad.png)
