### ISSUE TITLE
Using two types of buses in one line

### ISSUE THREAD

**Issue by braldoO** [klyte45/TransportLinesManager#91]
First of all, nice mod man, but after actualization still not sorting buses in lines, i like to put two types of buses to serve one line, but its only using one, i'm using the service vehicle 2 in my game too, maybe this mod is making the issue?

**Comment by klyte45** [comment]
SVS2 might be incompatible with TLM, once IPT2 also is. Try without it.

**Comment by klyte45** [comment]
Okay, it's a bug and I could reproduce here. Working in a fix yet this weekend

**Comment by braldoO** [comment]
Thanks for the heads up
