### ISSUE TITLE
Concern: wrong unbunching behavior near marked terminus

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#97]
The "bus skip stops" behavior introduced in TLM v14 has been the true "bus skip stops" dream that I have been dreaming about as I developed Express Bus Services. It was marvelous seeing how buses just skip stops seamlessly just like in real life. It was a dream come true.

(EBS remains relevant even after TLM v14, but that's another story.)

However, when I recently began making the compatibility between TLM and EBS, I encountered a confusing behavior, and, after debugging on my side to eliminate the problem on my side, I then notice a potential bug on your side that may contribute to the confusing behavior:

### Behavior
Buses never unbunch at marked termini (from TLM v14) when EBS (WIP) is enabled.

This is very bizarre and I double-checked my code a few times to make sure I did nothing wrong. And eventually, when I look at TLM, I discovered this problematic section of code at `TransportLineOverrides.cs`:

https://github.com/klyte45/TransportLinesManager/blob/21748d0a1d80805fec324fb6278787a00df6a93e/Overrides/TransportLineOverrides.cs#L326

It says:

- When:
  1. Express Buses is enabled; AND
  2. Current stop is NOT first stop; AND
  3. Next stop is NOT terminus
- Then:
  - Can depart

EBS (WIP) would have a different criteria at condition 3, and will instead check for "current stop is NOT terminus". This causes buses to not unbunch at termini as advertised: it makes them unbunch at one stop before the termini (EBS would force insta-depart), and when EBS wants them to stay at termini, TLM would tell them to depart (the `true` in the ` ? true : ` part).

(On a side note, when used with EBS (WIP), buses sometimes clump together physically at marked termini, i.e., multiple bus models would enter the same "slot" of bus stop even though there is already another bus there; could it be related to this potential bug? First-stop-in-line termini do not seem to have such physical bunching.)

**Comment by klyte45** [comment]
Fixed in current [alpha branch](https://github.com/klyte45/TransportLinesManager/tree/alpha/_requiredDLLs) version
